pull_request_rules:
   - name: automatic merge when author is dependabot
     conditions:
       - author=dependabot[bot]
       - check-success=build
       - base=main
     actions:
       merge:
         method: rebase
