TYPE_MAPPING: dict[str, str] = {
    'ppm': 'heart.rate',
    'km': 'distance',
    'm': 'distance',
    'cals': 'calories',
    'reps': 'reps',
    'w': 'power'
}

STEP_TYPES: dict[str, int] = {
    'warmup': 1,
    'cooldown': 2,
    'interval': 3,
    'recovery': 4,
    'repeat': 6,
    'rest': 5,
    'other': 7,
    'main': 8,
    }

SPORT_TYPES: dict[str, int] = {
    'running': 1,
    'cycling': 2,
    'swimming': 4,
    'strength_training': 5,
    'cardio_training': 6,
    'yoga': 7,
    'pilates': 8,
    'hiit': 9,
    'other': 3,
    }

INTENSITY_TYPES: dict[str, int] = {
    'active': 1,
    'rest': 2,
    'warmup': 3,
    'cooldown': 4,
    }

STEP_TYPES: dict[str, int] = {
    'warmup': 1,
    'cooldown': 2,
    'interval': 3,
    'recovery': 4,
    'rest': 5,
    'repeat': 6,
    'other': 7,
    'main': 8,
}

CONDITION_TYPES: dict[str, int] = {
    'calories': 4,
    'distance': 3,
    'heart.rate': 6,
    'lap.button': 1,
    'iterations': 7,
    'power': 5,
    'time': 2,
    'fixed.rest': 8,
    'fixed.repetition': 9,
    'reps': 10,
    'training.peaks.tss': 11,
    'repetition.time': 12,
    'time.at.valid.cda': 13,
    'power.last.lap': 14,
    'max.power.last.lap': 15,
    'repetition.swim.css.offset': 16,
    }

TARGET_TYPES: dict[str, int] = {
    'no.target': 1,
    'cadence': 3,
    'heart.rate.zone': 4,
    'pace.zone': 6,
    'power.zone': 2,
    'speed.zone': 5,
    'grade': 7,
    'heart.rate.lap': 8,
    'power.lap': 9,
    'power.3s': 10,
    'power.10s': 11,
    'power.30s': 12,
    'speed.lap': 13,
    'swim.stroke': 14,
    'resistance': 15,
    'power.curve': 16,
    'swim.instruction': 18,
    'swim.css.offset': 17,
    }

EQUIPMENT_TYPES: dict[str, int] = {
    'fins': 1,
    'kickboard': 2,
    'paddles': 3,
    'pull_buoy': 4,
    'snorkel': 5,
    }

STROKE_TYPES: dict[str, int] = {
    'any_stroke': 1,
    'backstroke': 2,
    'breaststroke': 3,
    'drill': 4,
    'fly': 5,
    'free': 6,
    'individual_medley': 7,
    'mixed': 8,
    'individual_medley_by_round': 9,
    'reverse_individual_medley_by_round': 10,
    }

SWIMINSTRUCTION_TYPES: dict[str, int] = {
    'recovery': 1,
    'very_easy': 2,
    'easy': 3,
    'moderate': 4,
    'hard': 5,
    'very_hard': 6,
    'all_out': 7,
    'fast': 8,
    'ascend': 9,
    'descend': 10,
    }

DRILL_TYPES: dict[str, int] = {
    'kick': 1,
    'pull': 2,
    'drill': 3,
    }

UNIT_TYPES: dict = {
    'meter': [1, 100.0],
    'kilometer': [2, 100000.0],
    'mile': [4, 160934.4],
    'kilogram': [8, 1000],
    'pound': [9, 453.59237],
    'yard': [230, 91.44],
}

ACTIVITY_TYPES: dict[str, int] = {
    'running': 1,
    'cycling': 2,
    'hiking': 3,
    'other': 4,
    'mountain_biking': 5,
    'trail_running': 6,
    'street_running': 7,
    'track_running': 8,
    'walking': 9,
    'road_biking': 10,
    'indoor_cardio': 11,
    'strength_training': 13,
    'casual_walking': 15,
    'speed_walking': 16,
    'all': 17,
    'treadmill_running': 18,
    'cyclocross': 19,
    'downhill_biking': 20,
    'track_cycling': 21,
    'recumbent_cycling': 22,
    'indoor_cycling': 25,
    'swimming': 26,
    'lap_swimming': 27,
    'open_water_swimming': 28,
    'fitness_equipment': 29,
    'elliptical': 30,
    'stair_climbing': 31,
    'indoor_rowing': 32,
    'mountaineering': 37,
    'wind_kite_surfing': 41,
    'horseback_riding': 44,
    'driving_general': 49,
    'flying': 52,
    'whitewater_rafting_kayaking': 60,
    'inline_skating': 63,
    'golf': 88,
    'multi_sport': 89,
    'steps': 108,
    'bmx': 131,
    'hunting_fishing': 133,
    'sky_diving': 134,
    'rc_drone': 136,
    'rock_climbing': 139,
    'hang_gliding': 140,
    'wingsuit_flying': 141,
    'gravel_cycling': 143,
    'diving': 144,
    'single_gas_diving': 145,
    'multi_gas_diving': 146,
    'gauge_diving': 147,
    'apnea_diving': 148,
    'floor_climbing': 150,
    'stop_watch': 151,
    'virtual_ride': 152,
    'virtual_run': 153,
    'obstacle_run': 154,
    'apnea_hunting': 155,
    'indoor_running': 156,
    'safety': 157,
    'assistance': 158,
    'incident_detected': 159,
    'pilates': 160,
    'ccr_diving': 161,
    'auto_racing': 162,
    'yoga': 163,
    'breathwork': 164,
    'winter_sports': 165,
    'snowmobiling_ws': 166,
    'snow_shoe_ws': 167,
    'skating_ws': 168,
    'backcountry_skiing_snowboarding_ws': 169,
    'skate_skiing_ws': 170,
    'cross_country_skiing_ws': 171,
    'resort_skiing_snowboarding_ws': 172,
    'indoor_climbing': 173,
    'bouldering': 174,
    'e_bike_mountain': 175,
    'e_bike_fitness': 176,
    'hiit': 180,
    'ultra_run': 181,
    'e_sport': 182,
    'motorcycling_v2': 185,
    'motocross_v2': 186,
    'atv_v2': 187,
    'transition_v2': 189,
    'swimToBikeTransition_v2': 190,
    'bikeToRunTransition_v2': 191,
    'runToBikeTransition_v2': 192,
    'hunting': 193,
    'hand_cycling': 197,
    'indoor_hand_cycling': 198,
    'para_sports': 199,
    'wheelchair_push_run': 200,
    'wheelchair_push_walk': 201,
    'meditation': 202,
    'backcountry_skiing': 203,
    'backcountry_snowboarding': 204,
    'disc_golf': 205,
    'team_sports': 206,
    'cricket': 207,
    'rugby': 208,
    'ice_hockey': 209,
    'field_hockey': 210,
    'lacrosse': 211,
    'volleyball': 212,
    'ultimate_disc': 213,
    'softball': 214,
    'soccer': 215,
    'american_football': 216,
    'basketball': 217,
    'baseball': 218,
    'racket_sports': 219,
    'table_tennis': 220,
    'platform_tennis': 221,
    'racquetball': 222,
    'squash': 223,
    'badminton': 224,
    'pickleball': 225,
    'paddelball': 226,
    'tennis_v2': 227,
    'water_sports': 228,
    'boating_v2': 229,
    'fishing_v2': 230,
    'kayaking_v2': 231,
    'kiteboarding_v2': 232,
    'offshore_grinding_v2': 233,
    'onshore_grinding_v2': 234,
    'paddling_v2': 235,
    'whitewater_rafting_v2': 236,
    'rowing_v2': 237,
    'sailing_v2': 238,
    'stand_up_paddleboarding_v2': 239,
    'surfing_v2': 240,
    'water_tubing': 241,
    'windsurfing_v2': 242,
    'wakeboarding_v2': 243,
    'wakesurfing': 244,
    'waterskiing': 245,
    'boxing': 246,
    'archery': 247,
    'mixed_martial_arts': 248,
    'overland': 249,
    'snorkeling': 250,
    'resort_skiing': 251,
    'resort_snowboarding': 252,
    'dance': 253,
    'jump_rope': 254,
    }

EVENT_TYPES: dict[str, int] = {
    'race': 1,
    'recreation': 2,
    'specialEvent': 3,
    'training': 4,
    'transportation': 5,
    'touring': 6,
    'geocaching': 7,
    'fitness': 8,
    'uncategorized': 9,
    }

GOLF_CLUB: dict[str, int] = {
    'Driver': 1,
    '3 Wood': 2,
    '5 Wood': 3,
    '1 Hybrid': 4,
    '2 Hybrid': 5,
    '3 Hybrid': 6,
    '4 Hybrid': 7,
    '5 Hybrid': 8,
    '6 Hybrid': 9,
    '1 Iron': 10,
    '2 Iron': 11,
    '3 Iron': 12,
    '4 Iron': 13,
    '5 Iron': 14,
    '6 Iron': 15,
    '7 Iron': 16,
    '8 Iron': 17,
    '9 Iron': 18,
    'Pitching Wedge': 19,
    'Gap Wedge': 20,
    'Sand Wedge': 21,
    'Lob Wedge': 22,
    'Putter': 23,
    }

GOLF_FLEX: dict[str, int] = {
    'Regular': 0,
    'Stiff': 1,
    'Extra Stiff': 2,
    'Senior': 3,
    'Ladies': 4,
    'Stiff/Regular': 5,
    }
