import pytest

from garminworkouts.config.generators.strength.lateral_raise import (
    _45_degree_cable_external_rotation_rep_generator,
    _45_degree_cable_external_rotation_hold_generator,
    alternating_lateral_raise_with_static_hold_rep_generator,
    alternating_lateral_raise_with_static_hold_hold_generator,
    bar_muscle_up_rep_generator,
    bar_muscle_up_hold_generator,
    bent_over_lateral_raise_rep_generator,
    bent_over_lateral_raise_hold_generator,
    cable_diagonal_raise_rep_generator,
    cable_diagonal_raise_hold_generator,
    cable_front_raise_rep_generator,
    cable_front_raise_hold_generator,
    calorie_row_rep_generator,
    calorie_row_hold_generator,
    combo_shoulder_raise_rep_generator,
    combo_shoulder_raise_hold_generator,
    dumbbell_diagonal_raise_rep_generator,
    dumbbell_diagonal_raise_hold_generator,
    dumbbell_lateral_raise_rep_generator,
    dumbbell_lateral_raise_hold_generator,
    dumbbell_v_raise_rep_generator,
    dumbbell_v_raise_hold_generator,
    front_raise_rep_generator,
    front_raise_hold_generator,
    leaning_dumbbell_lateral_raise_rep_generator,
    leaning_dumbbell_lateral_raise_hold_generator,
    lying_dumbbell_raise_rep_generator,
    lying_dumbbell_raise_hold_generator,
    muscle_up_rep_generator,
    muscle_up_hold_generator,
    one_arm_cable_lateral_raise_rep_generator,
    one_arm_cable_lateral_raise_hold_generator,
    overhand_grip_rear_lateral_raise_rep_generator,
    overhand_grip_rear_lateral_raise_hold_generator,
    plate_raises_rep_generator,
    plate_raises_hold_generator,
    ring_dip_rep_generator,
    ring_dip_hold_generator,
    ring_dip_kipping_rep_generator,
    ring_dip_kipping_hold_generator,
    ring_muscle_up_rep_generator,
    ring_muscle_up_hold_generator,
    rope_climb_rep_generator,
    rope_climb_hold_generator,
    scaption_rep_generator,
    scaption_hold_generator,
    seated_lateral_raise_rep_generator,
    seated_lateral_raise_hold_generator,
    seated_rear_lateral_raise_rep_generator,
    seated_rear_lateral_raise_hold_generator,
    side_lying_lateral_raise_rep_generator,
    side_lying_lateral_raise_hold_generator,
    standing_lift_rep_generator,
    standing_lift_hold_generator,
    suspended_row_rep_generator,
    suspended_row_hold_generator,
    underhand_grip_rear_lateral_raise_rep_generator,
    underhand_grip_rear_lateral_raise_hold_generator,
    wall_slide_rep_generator,
    wall_slide_hold_generator,
    wall_walk_rep_generator,
    wall_walk_hold_generator,
    weighted_ring_dip_rep_generator,
    weighted_ring_dip_hold_generator,
    weighted_ring_muscle_up_rep_generator,
    weighted_ring_muscle_up_hold_generator,
    weighted_rope_climb_rep_generator,
    weighted_rope_climb_hold_generator,
    weighted_wall_slide_rep_generator,
    weighted_wall_slide_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (_45_degree_cable_external_rotation_rep_generator, '_45_DEGREE_CABLE_EXTERNAL_ROTATION', 'reps'),
    (_45_degree_cable_external_rotation_hold_generator, '_45_DEGREE_CABLE_EXTERNAL_ROTATION', 'hold'),
    (alternating_lateral_raise_with_static_hold_rep_generator, 'ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD', 'reps'),
    (alternating_lateral_raise_with_static_hold_hold_generator, 'ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD', 'hold'),
    (bar_muscle_up_rep_generator, 'BAR_MUSCLE_UP', 'reps'),
    (bar_muscle_up_hold_generator, 'BAR_MUSCLE_UP', 'hold'),
    (bent_over_lateral_raise_rep_generator, 'BENT_OVER_LATERAL_RAISE', 'reps'),
    (bent_over_lateral_raise_hold_generator, 'BENT_OVER_LATERAL_RAISE', 'hold'),
    (cable_diagonal_raise_rep_generator, 'CABLE_DIAGONAL_RAISE', 'reps'),
    (cable_diagonal_raise_hold_generator, 'CABLE_DIAGONAL_RAISE', 'hold'),
    (cable_front_raise_rep_generator, 'CABLE_FRONT_RAISE', 'reps'),
    (cable_front_raise_hold_generator, 'CABLE_FRONT_RAISE', 'hold'),
    (calorie_row_rep_generator, 'CALORIE_ROW', 'reps'),
    (calorie_row_hold_generator, 'CALORIE_ROW', 'hold'),
    (combo_shoulder_raise_rep_generator, 'COMBO_SHOULDER_RAISE', 'reps'),
    (combo_shoulder_raise_hold_generator, 'COMBO_SHOULDER_RAISE', 'hold'),
    (dumbbell_diagonal_raise_rep_generator, 'DUMBBELL_DIAGONAL_RAISE', 'reps'),
    (dumbbell_diagonal_raise_hold_generator, 'DUMBBELL_DIAGONAL_RAISE', 'hold'),
    (dumbbell_lateral_raise_rep_generator, 'DUMBBELL_LATERAL_RAISE', 'reps'),
    (dumbbell_lateral_raise_hold_generator, 'DUMBBELL_LATERAL_RAISE', 'hold'),
    (dumbbell_v_raise_rep_generator, 'DUMBBELL_V_RAISE', 'reps'),
    (dumbbell_v_raise_hold_generator, 'DUMBBELL_V_RAISE', 'hold'),
    (front_raise_rep_generator, 'FRONT_RAISE', 'reps'),
    (front_raise_hold_generator, 'FRONT_RAISE', 'hold'),
    (leaning_dumbbell_lateral_raise_rep_generator, 'LEANING_DUMBBELL_LATERAL_RAISE', 'reps'),
    (leaning_dumbbell_lateral_raise_hold_generator, 'LEANING_DUMBBELL_LATERAL_RAISE', 'hold'),
    (lying_dumbbell_raise_rep_generator, 'LYING_DUMBBELL_RAISE', 'reps'),
    (lying_dumbbell_raise_hold_generator, 'LYING_DUMBBELL_RAISE', 'hold'),
    (muscle_up_rep_generator, 'MUSCLE_UP', 'reps'),
    (muscle_up_hold_generator, 'MUSCLE_UP', 'hold'),
    (one_arm_cable_lateral_raise_rep_generator, 'ONE_ARM_CABLE_LATERAL_RAISE', 'reps'),
    (one_arm_cable_lateral_raise_hold_generator, 'ONE_ARM_CABLE_LATERAL_RAISE', 'hold'),
    (overhand_grip_rear_lateral_raise_rep_generator, 'OVERHAND_GRIP_REAR_LATERAL_RAISE', 'reps'),
    (overhand_grip_rear_lateral_raise_hold_generator, 'OVERHAND_GRIP_REAR_LATERAL_RAISE', 'hold'),
    (plate_raises_rep_generator, 'PLATE_RAISES', 'reps'),
    (plate_raises_hold_generator, 'PLATE_RAISES', 'hold'),
    (ring_dip_rep_generator, 'RING_DIP', 'reps'),
    (ring_dip_hold_generator, 'RING_DIP', 'hold'),
    (ring_dip_kipping_rep_generator, 'RING_DIP_KIPPING', 'reps'),
    (ring_dip_kipping_hold_generator, 'RING_DIP_KIPPING', 'hold'),
    (ring_muscle_up_rep_generator, 'RING_MUSCLE_UP', 'reps'),
    (ring_muscle_up_hold_generator, 'RING_MUSCLE_UP', 'hold'),
    (rope_climb_rep_generator, 'ROPE_CLIMB', 'reps'),
    (rope_climb_hold_generator, 'ROPE_CLIMB', 'hold'),
    (scaption_rep_generator, 'SCAPTION', 'reps'),
    (scaption_hold_generator, 'SCAPTION', 'hold'),
    (seated_lateral_raise_rep_generator, 'SEATED_LATERAL_RAISE', 'reps'),
    (seated_lateral_raise_hold_generator, 'SEATED_LATERAL_RAISE', 'hold'),
    (seated_rear_lateral_raise_rep_generator, 'SEATED_REAR_LATERAL_RAISE', 'reps'),
    (seated_rear_lateral_raise_hold_generator, 'SEATED_REAR_LATERAL_RAISE', 'hold'),
    (side_lying_lateral_raise_rep_generator, 'SIDE_LYING_LATERAL_RAISE', 'reps'),
    (side_lying_lateral_raise_hold_generator, 'SIDE_LYING_LATERAL_RAISE', 'hold'),
    (standing_lift_rep_generator, 'STANDING_LIFT', 'reps'),
    (standing_lift_hold_generator, 'STANDING_LIFT', 'hold'),
    (suspended_row_rep_generator, 'SUSPENDED_ROW', 'reps'),
    (suspended_row_hold_generator, 'SUSPENDED_ROW', 'hold'),
    (underhand_grip_rear_lateral_raise_rep_generator, 'UNDERHAND_GRIP_REAR_LATERAL_RAISE', 'reps'),
    (underhand_grip_rear_lateral_raise_hold_generator, 'UNDERHAND_GRIP_REAR_LATERAL_RAISE', 'hold'),
    (wall_slide_rep_generator, 'WALL_SLIDE', 'reps'),
    (wall_slide_hold_generator, 'WALL_SLIDE', 'hold'),
    (wall_walk_rep_generator, 'WALL_WALK', 'reps'),
    (wall_walk_hold_generator, 'WALL_WALK', 'hold'),
    (weighted_ring_dip_rep_generator, 'WEIGHTED_RING_DIP', 'reps'),
    (weighted_ring_dip_hold_generator, 'WEIGHTED_RING_DIP', 'hold'),
    (weighted_ring_muscle_up_rep_generator, 'WEIGHTED_RING_MUSCLE_UP', 'reps'),
    (weighted_ring_muscle_up_hold_generator, 'WEIGHTED_RING_MUSCLE_UP', 'hold'),
    (weighted_rope_climb_rep_generator, 'WEIGHTED_ROPE_CLIMB', 'reps'),
    (weighted_rope_climb_hold_generator, 'WEIGHTED_ROPE_CLIMB', 'hold'),
    (weighted_wall_slide_rep_generator, 'WEIGHTED_WALL_SLIDE', 'reps'),
    (weighted_wall_slide_hold_generator, 'WEIGHTED_WALL_SLIDE', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'LATERAL_RAISE'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
