import pytest

from garminworkouts.config.generators.strength.lunge import (
    alternating_barbell_forward_lunge_rep_generator,
    alternating_barbell_forward_lunge_hold_generator,
    alternating_dumbbell_lunge_rep_generator,
    alternating_dumbbell_lunge_hold_generator,
    alternating_dumbbell_lunge_with_reach_rep_generator,
    alternating_dumbbell_lunge_with_reach_hold_generator,
    back_foot_elevated_dumbbell_split_squat_rep_generator,
    back_foot_elevated_dumbbell_split_squat_hold_generator,
    barbell_box_lunge_rep_generator,
    barbell_box_lunge_hold_generator,
    barbell_bulgarian_split_squat_rep_generator,
    barbell_bulgarian_split_squat_hold_generator,
    barbell_crossover_lunge_rep_generator,
    barbell_crossover_lunge_hold_generator,
    barbell_front_split_squat_rep_generator,
    barbell_front_split_squat_hold_generator,
    barbell_lunge_rep_generator,
    barbell_lunge_hold_generator,
    barbell_reverse_lunge_rep_generator,
    barbell_reverse_lunge_hold_generator,
    barbell_side_lunge_rep_generator,
    barbell_side_lunge_hold_generator,
    barbell_split_squat_rep_generator,
    barbell_split_squat_hold_generator,
    core_control_rear_lunge_rep_generator,
    core_control_rear_lunge_hold_generator,
    curtsy_lunge_rep_generator,
    curtsy_lunge_hold_generator,
    diagonal_lunge_rep_generator,
    diagonal_lunge_hold_generator,
    drop_lunge_rep_generator,
    drop_lunge_hold_generator,
    dumbbell_box_lunge_rep_generator,
    dumbbell_box_lunge_hold_generator,
    dumbbell_bulgarian_split_squat_rep_generator,
    dumbbell_bulgarian_split_squat_hold_generator,
    dumbbell_crossover_lunge_rep_generator,
    dumbbell_crossover_lunge_hold_generator,
    dumbbell_diagonal_lunge_rep_generator,
    dumbbell_diagonal_lunge_hold_generator,
    dumbbell_lunge_rep_generator,
    dumbbell_lunge_hold_generator,
    dumbbell_lunge_and_rotation_rep_generator,
    dumbbell_lunge_and_rotation_hold_generator,
    dumbbell_overhead_bulgarian_split_squat_rep_generator,
    dumbbell_overhead_bulgarian_split_squat_hold_generator,
    dumbbell_overhead_walking_lunge_rep_generator,
    dumbbell_overhead_walking_lunge_hold_generator,
    dumbbell_reverse_lunge_rep_generator,
    dumbbell_reverse_lunge_hold_generator,
    dumbbell_reverse_lunge_to_high_knee_and_press_rep_generator,
    dumbbell_reverse_lunge_to_high_knee_and_press_hold_generator,
    dumbbell_side_lunge_rep_generator,
    dumbbell_side_lunge_hold_generator,
    elevated_front_foot_barbell_split_squat_rep_generator,
    elevated_front_foot_barbell_split_squat_hold_generator,
    front_foot_elevated_dumbbell_split_squat_rep_generator,
    front_foot_elevated_dumbbell_split_squat_hold_generator,
    gunslinger_lunge_rep_generator,
    gunslinger_lunge_hold_generator,
    lawnmower_lunge_rep_generator,
    lawnmower_lunge_hold_generator,
    low_lunge_with_isometric_adduction_rep_generator,
    low_lunge_with_isometric_adduction_hold_generator,
    low_side_to_side_lunge_rep_generator,
    low_side_to_side_lunge_hold_generator,
    lunge_rep_generator,
    lunge_hold_generator,
    lunge_matrix_rep_generator,
    lunge_matrix_hold_generator,
    lunge_with_arm_reach_rep_generator,
    lunge_with_arm_reach_hold_generator,
    lunge_with_diagonal_reach_rep_generator,
    lunge_with_diagonal_reach_hold_generator,
    lunge_with_side_bend_rep_generator,
    lunge_with_side_bend_hold_generator,
    offset_dumbbell_lunge_rep_generator,
    offset_dumbbell_lunge_hold_generator,
    offset_dumbbell_reverse_lunge_rep_generator,
    offset_dumbbell_reverse_lunge_hold_generator,
    overhead_bulgarian_split_squat_rep_generator,
    overhead_bulgarian_split_squat_hold_generator,
    overhead_dumbbell_lunge_rep_generator,
    overhead_dumbbell_lunge_hold_generator,
    overhead_dumbbell_reverse_lunge_rep_generator,
    overhead_dumbbell_reverse_lunge_hold_generator,
    overhead_dumbbell_split_squat_rep_generator,
    overhead_dumbbell_split_squat_hold_generator,
    overhead_lunge_rep_generator,
    overhead_lunge_hold_generator,
    overhead_lunge_with_rotation_rep_generator,
    overhead_lunge_with_rotation_hold_generator,
    reverse_barbell_box_lunge_rep_generator,
    reverse_barbell_box_lunge_hold_generator,
    reverse_box_lunge_rep_generator,
    reverse_box_lunge_hold_generator,
    reverse_dumbbell_box_lunge_rep_generator,
    reverse_dumbbell_box_lunge_hold_generator,
    reverse_dumbbell_crossover_lunge_rep_generator,
    reverse_dumbbell_crossover_lunge_hold_generator,
    reverse_dumbbell_diagonal_lunge_rep_generator,
    reverse_dumbbell_diagonal_lunge_hold_generator,
    reverse_lunge_with_reach_back_rep_generator,
    reverse_lunge_with_reach_back_hold_generator,
    reverse_lunge_with_twist_and_overhead_reach_rep_generator,
    reverse_lunge_with_twist_and_overhead_reach_hold_generator,
    reverse_sliding_box_lunge_rep_generator,
    reverse_sliding_box_lunge_hold_generator,
    reverse_sliding_lunge_rep_generator,
    reverse_sliding_lunge_hold_generator,
    runners_lunge_to_balance_rep_generator,
    runners_lunge_to_balance_hold_generator,
    scissor_power_switch_rep_generator,
    scissor_power_switch_hold_generator,
    shifting_side_lunge_rep_generator,
    shifting_side_lunge_hold_generator,
    side_and_crossover_lunge_rep_generator,
    side_and_crossover_lunge_hold_generator,
    side_lunge_rep_generator,
    side_lunge_hold_generator,
    side_lunge_and_press_rep_generator,
    side_lunge_and_press_hold_generator,
    side_lunge_jump_off_rep_generator,
    side_lunge_jump_off_hold_generator,
    side_lunge_sweep_rep_generator,
    side_lunge_sweep_hold_generator,
    side_lunge_to_crossover_tap_rep_generator,
    side_lunge_to_crossover_tap_hold_generator,
    side_to_side_lunge_chops_rep_generator,
    side_to_side_lunge_chops_hold_generator,
    siff_jump_lunge_rep_generator,
    siff_jump_lunge_hold_generator,
    single_arm_reverse_lunge_and_press_rep_generator,
    single_arm_reverse_lunge_and_press_hold_generator,
    sliding_lateral_lunge_rep_generator,
    sliding_lateral_lunge_hold_generator,
    walking_barbell_lunge_rep_generator,
    walking_barbell_lunge_hold_generator,
    walking_dumbbell_lunge_rep_generator,
    walking_dumbbell_lunge_hold_generator,
    walking_lunge_rep_generator,
    walking_lunge_hold_generator,
    weighted_curtsy_lunge_rep_generator,
    weighted_curtsy_lunge_hold_generator,
    weighted_lunge_rep_generator,
    weighted_lunge_hold_generator,
    weighted_lunge_matrix_rep_generator,
    weighted_lunge_matrix_hold_generator,
    weighted_reverse_lunge_with_reach_back_rep_generator,
    weighted_reverse_lunge_with_reach_back_hold_generator,
    weighted_reverse_lunge_with_twist_and_overhead_reach_rep_generator,
    weighted_reverse_lunge_with_twist_and_overhead_reach_hold_generator,
    weighted_reverse_sliding_box_lunge_rep_generator,
    weighted_reverse_sliding_box_lunge_hold_generator,
    weighted_reverse_sliding_lunge_rep_generator,
    weighted_reverse_sliding_lunge_hold_generator,
    weighted_runners_lunge_to_balance_rep_generator,
    weighted_runners_lunge_to_balance_hold_generator,
    weighted_shifting_side_lunge_rep_generator,
    weighted_shifting_side_lunge_hold_generator,
    weighted_side_and_crossover_lunge_rep_generator,
    weighted_side_and_crossover_lunge_hold_generator,
    weighted_side_lunge_rep_generator,
    weighted_side_lunge_hold_generator,
    weighted_side_lunge_and_press_rep_generator,
    weighted_side_lunge_and_press_hold_generator,
    weighted_side_lunge_jump_off_rep_generator,
    weighted_side_lunge_jump_off_hold_generator,
    weighted_side_lunge_sweep_rep_generator,
    weighted_side_lunge_sweep_hold_generator,
    weighted_side_lunge_to_crossover_tap_rep_generator,
    weighted_side_lunge_to_crossover_tap_hold_generator,
    weighted_side_to_side_lunge_chops_rep_generator,
    weighted_side_to_side_lunge_chops_hold_generator,
    weighted_siff_jump_lunge_rep_generator,
    weighted_siff_jump_lunge_hold_generator,
    weighted_sliding_lateral_lunge_rep_generator,
    weighted_sliding_lateral_lunge_hold_generator,
    weighted_walking_lunge_rep_generator,
    weighted_walking_lunge_hold_generator,
    wide_grip_overhead_barbell_split_squat_rep_generator,
    wide_grip_overhead_barbell_split_squat_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (alternating_barbell_forward_lunge_rep_generator, 'ALTERNATING_BARBELL_FORWARD_LUNGE', 'reps'),
    (alternating_barbell_forward_lunge_hold_generator, 'ALTERNATING_BARBELL_FORWARD_LUNGE', 'hold'),
    (alternating_dumbbell_lunge_rep_generator, 'ALTERNATING_DUMBBELL_LUNGE', 'reps'),
    (alternating_dumbbell_lunge_hold_generator, 'ALTERNATING_DUMBBELL_LUNGE', 'hold'),
    (alternating_dumbbell_lunge_with_reach_rep_generator, 'ALTERNATING_DUMBBELL_LUNGE_WITH_REACH', 'reps'),
    (alternating_dumbbell_lunge_with_reach_hold_generator, 'ALTERNATING_DUMBBELL_LUNGE_WITH_REACH', 'hold'),
    (back_foot_elevated_dumbbell_split_squat_rep_generator, 'BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT', 'reps'),
    (back_foot_elevated_dumbbell_split_squat_hold_generator, 'BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT', 'hold'),
    (barbell_box_lunge_rep_generator, 'BARBELL_BOX_LUNGE', 'reps'),
    (barbell_box_lunge_hold_generator, 'BARBELL_BOX_LUNGE', 'hold'),
    (barbell_bulgarian_split_squat_rep_generator, 'BARBELL_BULGARIAN_SPLIT_SQUAT', 'reps'),
    (barbell_bulgarian_split_squat_hold_generator, 'BARBELL_BULGARIAN_SPLIT_SQUAT', 'hold'),
    (barbell_crossover_lunge_rep_generator, 'BARBELL_CROSSOVER_LUNGE', 'reps'),
    (barbell_crossover_lunge_hold_generator, 'BARBELL_CROSSOVER_LUNGE', 'hold'),
    (barbell_front_split_squat_rep_generator, 'BARBELL_FRONT_SPLIT_SQUAT', 'reps'),
    (barbell_front_split_squat_hold_generator, 'BARBELL_FRONT_SPLIT_SQUAT', 'hold'),
    (barbell_lunge_rep_generator, 'BARBELL_LUNGE', 'reps'),
    (barbell_lunge_hold_generator, 'BARBELL_LUNGE', 'hold'),
    (barbell_reverse_lunge_rep_generator, 'BARBELL_REVERSE_LUNGE', 'reps'),
    (barbell_reverse_lunge_hold_generator, 'BARBELL_REVERSE_LUNGE', 'hold'),
    (barbell_side_lunge_rep_generator, 'BARBELL_SIDE_LUNGE', 'reps'),
    (barbell_side_lunge_hold_generator, 'BARBELL_SIDE_LUNGE', 'hold'),
    (barbell_split_squat_rep_generator, 'BARBELL_SPLIT_SQUAT', 'reps'),
    (barbell_split_squat_hold_generator, 'BARBELL_SPLIT_SQUAT', 'hold'),
    (core_control_rear_lunge_rep_generator, 'CORE_CONTROL_REAR_LUNGE', 'reps'),
    (core_control_rear_lunge_hold_generator, 'CORE_CONTROL_REAR_LUNGE', 'hold'),
    (curtsy_lunge_rep_generator, 'CURTSY_LUNGE', 'reps'),
    (curtsy_lunge_hold_generator, 'CURTSY_LUNGE', 'hold'),
    (diagonal_lunge_rep_generator, 'DIAGONAL_LUNGE', 'reps'),
    (diagonal_lunge_hold_generator, 'DIAGONAL_LUNGE', 'hold'),
    (drop_lunge_rep_generator, 'DROP_LUNGE', 'reps'),
    (drop_lunge_hold_generator, 'DROP_LUNGE', 'hold'),
    (dumbbell_box_lunge_rep_generator, 'DUMBBELL_BOX_LUNGE', 'reps'),
    (dumbbell_box_lunge_hold_generator, 'DUMBBELL_BOX_LUNGE', 'hold'),
    (dumbbell_bulgarian_split_squat_rep_generator, 'DUMBBELL_BULGARIAN_SPLIT_SQUAT', 'reps'),
    (dumbbell_bulgarian_split_squat_hold_generator, 'DUMBBELL_BULGARIAN_SPLIT_SQUAT', 'hold'),
    (dumbbell_crossover_lunge_rep_generator, 'DUMBBELL_CROSSOVER_LUNGE', 'reps'),
    (dumbbell_crossover_lunge_hold_generator, 'DUMBBELL_CROSSOVER_LUNGE', 'hold'),
    (dumbbell_diagonal_lunge_rep_generator, 'DUMBBELL_DIAGONAL_LUNGE', 'reps'),
    (dumbbell_diagonal_lunge_hold_generator, 'DUMBBELL_DIAGONAL_LUNGE', 'hold'),
    (dumbbell_lunge_rep_generator, 'DUMBBELL_LUNGE', 'reps'),
    (dumbbell_lunge_hold_generator, 'DUMBBELL_LUNGE', 'hold'),
    (dumbbell_lunge_and_rotation_rep_generator, 'DUMBBELL_LUNGE_AND_ROTATION', 'reps'),
    (dumbbell_lunge_and_rotation_hold_generator, 'DUMBBELL_LUNGE_AND_ROTATION', 'hold'),
    (dumbbell_overhead_bulgarian_split_squat_rep_generator, 'DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT', 'reps'),
    (dumbbell_overhead_bulgarian_split_squat_hold_generator, 'DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT', 'hold'),
    (dumbbell_overhead_walking_lunge_rep_generator, 'DUMBBELL_OVERHEAD_WALKING_LUNGE', 'reps'),
    (dumbbell_overhead_walking_lunge_hold_generator, 'DUMBBELL_OVERHEAD_WALKING_LUNGE', 'hold'),
    (dumbbell_reverse_lunge_rep_generator, 'DUMBBELL_REVERSE_LUNGE', 'reps'),
    (dumbbell_reverse_lunge_hold_generator, 'DUMBBELL_REVERSE_LUNGE', 'hold'),
    (dumbbell_reverse_lunge_to_high_knee_and_press_rep_generator, 'DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS', 'reps'),
    (dumbbell_reverse_lunge_to_high_knee_and_press_hold_generator, 'DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS', 'hold'),
    (dumbbell_side_lunge_rep_generator, 'DUMBBELL_SIDE_LUNGE', 'reps'),
    (dumbbell_side_lunge_hold_generator, 'DUMBBELL_SIDE_LUNGE', 'hold'),
    (elevated_front_foot_barbell_split_squat_rep_generator, 'ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT', 'reps'),
    (elevated_front_foot_barbell_split_squat_hold_generator, 'ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT', 'hold'),
    (front_foot_elevated_dumbbell_split_squat_rep_generator, 'FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT', 'reps'),
    (front_foot_elevated_dumbbell_split_squat_hold_generator, 'FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT', 'hold'),
    (gunslinger_lunge_rep_generator, 'GUNSLINGER_LUNGE', 'reps'),
    (gunslinger_lunge_hold_generator, 'GUNSLINGER_LUNGE', 'hold'),
    (lawnmower_lunge_rep_generator, 'LAWNMOWER_LUNGE', 'reps'),
    (lawnmower_lunge_hold_generator, 'LAWNMOWER_LUNGE', 'hold'),
    (low_lunge_with_isometric_adduction_rep_generator, 'LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION', 'reps'),
    (low_lunge_with_isometric_adduction_hold_generator, 'LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION', 'hold'),
    (low_side_to_side_lunge_rep_generator, 'LOW_SIDE_TO_SIDE_LUNGE', 'reps'),
    (low_side_to_side_lunge_hold_generator, 'LOW_SIDE_TO_SIDE_LUNGE', 'hold'),
    (lunge_rep_generator, 'LUNGE', 'reps'),
    (lunge_hold_generator, 'LUNGE', 'hold'),
    (lunge_matrix_rep_generator, 'LUNGE_MATRIX', 'reps'),
    (lunge_matrix_hold_generator, 'LUNGE_MATRIX', 'hold'),
    (lunge_with_arm_reach_rep_generator, 'LUNGE_WITH_ARM_REACH', 'reps'),
    (lunge_with_arm_reach_hold_generator, 'LUNGE_WITH_ARM_REACH', 'hold'),
    (lunge_with_diagonal_reach_rep_generator, 'LUNGE_WITH_DIAGONAL_REACH', 'reps'),
    (lunge_with_diagonal_reach_hold_generator, 'LUNGE_WITH_DIAGONAL_REACH', 'hold'),
    (lunge_with_side_bend_rep_generator, 'LUNGE_WITH_SIDE_BEND', 'reps'),
    (lunge_with_side_bend_hold_generator, 'LUNGE_WITH_SIDE_BEND', 'hold'),
    (offset_dumbbell_lunge_rep_generator, 'OFFSET_DUMBBELL_LUNGE', 'reps'),
    (offset_dumbbell_lunge_hold_generator, 'OFFSET_DUMBBELL_LUNGE', 'hold'),
    (offset_dumbbell_reverse_lunge_rep_generator, 'OFFSET_DUMBBELL_REVERSE_LUNGE', 'reps'),
    (offset_dumbbell_reverse_lunge_hold_generator, 'OFFSET_DUMBBELL_REVERSE_LUNGE', 'hold'),
    (overhead_bulgarian_split_squat_rep_generator, 'OVERHEAD_BULGARIAN_SPLIT_SQUAT', 'reps'),
    (overhead_bulgarian_split_squat_hold_generator, 'OVERHEAD_BULGARIAN_SPLIT_SQUAT', 'hold'),
    (overhead_dumbbell_lunge_rep_generator, 'OVERHEAD_DUMBBELL_LUNGE', 'reps'),
    (overhead_dumbbell_lunge_hold_generator, 'OVERHEAD_DUMBBELL_LUNGE', 'hold'),
    (overhead_dumbbell_reverse_lunge_rep_generator, 'OVERHEAD_DUMBBELL_REVERSE_LUNGE', 'reps'),
    (overhead_dumbbell_reverse_lunge_hold_generator, 'OVERHEAD_DUMBBELL_REVERSE_LUNGE', 'hold'),
    (overhead_dumbbell_split_squat_rep_generator, 'OVERHEAD_DUMBBELL_SPLIT_SQUAT', 'reps'),
    (overhead_dumbbell_split_squat_hold_generator, 'OVERHEAD_DUMBBELL_SPLIT_SQUAT', 'hold'),
    (overhead_lunge_rep_generator, 'OVERHEAD_LUNGE', 'reps'),
    (overhead_lunge_hold_generator, 'OVERHEAD_LUNGE', 'hold'),
    (overhead_lunge_with_rotation_rep_generator, 'OVERHEAD_LUNGE_WITH_ROTATION', 'reps'),
    (overhead_lunge_with_rotation_hold_generator, 'OVERHEAD_LUNGE_WITH_ROTATION', 'hold'),
    (reverse_barbell_box_lunge_rep_generator, 'REVERSE_BARBELL_BOX_LUNGE', 'reps'),
    (reverse_barbell_box_lunge_hold_generator, 'REVERSE_BARBELL_BOX_LUNGE', 'hold'),
    (reverse_box_lunge_rep_generator, 'REVERSE_BOX_LUNGE', 'reps'),
    (reverse_box_lunge_hold_generator, 'REVERSE_BOX_LUNGE', 'hold'),
    (reverse_dumbbell_box_lunge_rep_generator, 'REVERSE_DUMBBELL_BOX_LUNGE', 'reps'),
    (reverse_dumbbell_box_lunge_hold_generator, 'REVERSE_DUMBBELL_BOX_LUNGE', 'hold'),
    (reverse_dumbbell_crossover_lunge_rep_generator, 'REVERSE_DUMBBELL_CROSSOVER_LUNGE', 'reps'),
    (reverse_dumbbell_crossover_lunge_hold_generator, 'REVERSE_DUMBBELL_CROSSOVER_LUNGE', 'hold'),
    (reverse_dumbbell_diagonal_lunge_rep_generator, 'REVERSE_DUMBBELL_DIAGONAL_LUNGE', 'reps'),
    (reverse_dumbbell_diagonal_lunge_hold_generator, 'REVERSE_DUMBBELL_DIAGONAL_LUNGE', 'hold'),
    (reverse_lunge_with_reach_back_rep_generator, 'REVERSE_LUNGE_WITH_REACH_BACK', 'reps'),
    (reverse_lunge_with_reach_back_hold_generator, 'REVERSE_LUNGE_WITH_REACH_BACK', 'hold'),
    (reverse_lunge_with_twist_and_overhead_reach_rep_generator, 'REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH', 'reps'),
    (reverse_lunge_with_twist_and_overhead_reach_hold_generator, 'REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH', 'hold'),
    (reverse_sliding_box_lunge_rep_generator, 'REVERSE_SLIDING_BOX_LUNGE', 'reps'),
    (reverse_sliding_box_lunge_hold_generator, 'REVERSE_SLIDING_BOX_LUNGE', 'hold'),
    (reverse_sliding_lunge_rep_generator, 'REVERSE_SLIDING_LUNGE', 'reps'),
    (reverse_sliding_lunge_hold_generator, 'REVERSE_SLIDING_LUNGE', 'hold'),
    (runners_lunge_to_balance_rep_generator, 'RUNNERS_LUNGE_TO_BALANCE', 'reps'),
    (runners_lunge_to_balance_hold_generator, 'RUNNERS_LUNGE_TO_BALANCE', 'hold'),
    (scissor_power_switch_rep_generator, 'SCISSOR_POWER_SWITCH', 'reps'),
    (scissor_power_switch_hold_generator, 'SCISSOR_POWER_SWITCH', 'hold'),
    (shifting_side_lunge_rep_generator, 'SHIFTING_SIDE_LUNGE', 'reps'),
    (shifting_side_lunge_hold_generator, 'SHIFTING_SIDE_LUNGE', 'hold'),
    (side_and_crossover_lunge_rep_generator, 'SIDE_AND_CROSSOVER_LUNGE', 'reps'),
    (side_and_crossover_lunge_hold_generator, 'SIDE_AND_CROSSOVER_LUNGE', 'hold'),
    (side_lunge_rep_generator, 'SIDE_LUNGE', 'reps'),
    (side_lunge_hold_generator, 'SIDE_LUNGE', 'hold'),
    (side_lunge_and_press_rep_generator, 'SIDE_LUNGE_AND_PRESS', 'reps'),
    (side_lunge_and_press_hold_generator, 'SIDE_LUNGE_AND_PRESS', 'hold'),
    (side_lunge_jump_off_rep_generator, 'SIDE_LUNGE_JUMP_OFF', 'reps'),
    (side_lunge_jump_off_hold_generator, 'SIDE_LUNGE_JUMP_OFF', 'hold'),
    (side_lunge_sweep_rep_generator, 'SIDE_LUNGE_SWEEP', 'reps'),
    (side_lunge_sweep_hold_generator, 'SIDE_LUNGE_SWEEP', 'hold'),
    (side_lunge_to_crossover_tap_rep_generator, 'SIDE_LUNGE_TO_CROSSOVER_TAP', 'reps'),
    (side_lunge_to_crossover_tap_hold_generator, 'SIDE_LUNGE_TO_CROSSOVER_TAP', 'hold'),
    (side_to_side_lunge_chops_rep_generator, 'SIDE_TO_SIDE_LUNGE_CHOPS', 'reps'),
    (side_to_side_lunge_chops_hold_generator, 'SIDE_TO_SIDE_LUNGE_CHOPS', 'hold'),
    (siff_jump_lunge_rep_generator, 'SIFF_JUMP_LUNGE', 'reps'),
    (siff_jump_lunge_hold_generator, 'SIFF_JUMP_LUNGE', 'hold'),
    (single_arm_reverse_lunge_and_press_rep_generator, 'SINGLE_ARM_REVERSE_LUNGE_AND_PRESS', 'reps'),
    (single_arm_reverse_lunge_and_press_hold_generator, 'SINGLE_ARM_REVERSE_LUNGE_AND_PRESS', 'hold'),
    (sliding_lateral_lunge_rep_generator, 'SLIDING_LATERAL_LUNGE', 'reps'),
    (sliding_lateral_lunge_hold_generator, 'SLIDING_LATERAL_LUNGE', 'hold'),
    (walking_barbell_lunge_rep_generator, 'WALKING_BARBELL_LUNGE', 'reps'),
    (walking_barbell_lunge_hold_generator, 'WALKING_BARBELL_LUNGE', 'hold'),
    (walking_dumbbell_lunge_rep_generator, 'WALKING_DUMBBELL_LUNGE', 'reps'),
    (walking_dumbbell_lunge_hold_generator, 'WALKING_DUMBBELL_LUNGE', 'hold'),
    (walking_lunge_rep_generator, 'WALKING_LUNGE', 'reps'),
    (walking_lunge_hold_generator, 'WALKING_LUNGE', 'hold'),
    (weighted_curtsy_lunge_rep_generator, 'WEIGHTED_CURTSY_LUNGE', 'reps'),
    (weighted_curtsy_lunge_hold_generator, 'WEIGHTED_CURTSY_LUNGE', 'hold'),
    (weighted_lunge_rep_generator, 'WEIGHTED_LUNGE', 'reps'),
    (weighted_lunge_hold_generator, 'WEIGHTED_LUNGE', 'hold'),
    (weighted_lunge_matrix_rep_generator, 'WEIGHTED_LUNGE_MATRIX', 'reps'),
    (weighted_lunge_matrix_hold_generator, 'WEIGHTED_LUNGE_MATRIX', 'hold'),
    (weighted_reverse_lunge_with_reach_back_rep_generator, 'WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK', 'reps'),
    (weighted_reverse_lunge_with_reach_back_hold_generator, 'WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK', 'hold'),
    (weighted_reverse_lunge_with_twist_and_overhead_reach_rep_generator, 'WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH', 'reps'),
    (weighted_reverse_lunge_with_twist_and_overhead_reach_hold_generator, 'WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH', 'hold'),
    (weighted_reverse_sliding_box_lunge_rep_generator, 'WEIGHTED_REVERSE_SLIDING_BOX_LUNGE', 'reps'),
    (weighted_reverse_sliding_box_lunge_hold_generator, 'WEIGHTED_REVERSE_SLIDING_BOX_LUNGE', 'hold'),
    (weighted_reverse_sliding_lunge_rep_generator, 'WEIGHTED_REVERSE_SLIDING_LUNGE', 'reps'),
    (weighted_reverse_sliding_lunge_hold_generator, 'WEIGHTED_REVERSE_SLIDING_LUNGE', 'hold'),
    (weighted_runners_lunge_to_balance_rep_generator, 'WEIGHTED_RUNNERS_LUNGE_TO_BALANCE', 'reps'),
    (weighted_runners_lunge_to_balance_hold_generator, 'WEIGHTED_RUNNERS_LUNGE_TO_BALANCE', 'hold'),
    (weighted_shifting_side_lunge_rep_generator, 'WEIGHTED_SHIFTING_SIDE_LUNGE', 'reps'),
    (weighted_shifting_side_lunge_hold_generator, 'WEIGHTED_SHIFTING_SIDE_LUNGE', 'hold'),
    (weighted_side_and_crossover_lunge_rep_generator, 'WEIGHTED_SIDE_AND_CROSSOVER_LUNGE', 'reps'),
    (weighted_side_and_crossover_lunge_hold_generator, 'WEIGHTED_SIDE_AND_CROSSOVER_LUNGE', 'hold'),
    (weighted_side_lunge_rep_generator, 'WEIGHTED_SIDE_LUNGE', 'reps'),
    (weighted_side_lunge_hold_generator, 'WEIGHTED_SIDE_LUNGE', 'hold'),
    (weighted_side_lunge_and_press_rep_generator, 'WEIGHTED_SIDE_LUNGE_AND_PRESS', 'reps'),
    (weighted_side_lunge_and_press_hold_generator, 'WEIGHTED_SIDE_LUNGE_AND_PRESS', 'hold'),
    (weighted_side_lunge_jump_off_rep_generator, 'WEIGHTED_SIDE_LUNGE_JUMP_OFF', 'reps'),
    (weighted_side_lunge_jump_off_hold_generator, 'WEIGHTED_SIDE_LUNGE_JUMP_OFF', 'hold'),
    (weighted_side_lunge_sweep_rep_generator, 'WEIGHTED_SIDE_LUNGE_SWEEP', 'reps'),
    (weighted_side_lunge_sweep_hold_generator, 'WEIGHTED_SIDE_LUNGE_SWEEP', 'hold'),
    (weighted_side_lunge_to_crossover_tap_rep_generator, 'WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP', 'reps'),
    (weighted_side_lunge_to_crossover_tap_hold_generator, 'WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP', 'hold'),
    (weighted_side_to_side_lunge_chops_rep_generator, 'WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS', 'reps'),
    (weighted_side_to_side_lunge_chops_hold_generator, 'WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS', 'hold'),
    (weighted_siff_jump_lunge_rep_generator, 'WEIGHTED_SIFF_JUMP_LUNGE', 'reps'),
    (weighted_siff_jump_lunge_hold_generator, 'WEIGHTED_SIFF_JUMP_LUNGE', 'hold'),
    (weighted_sliding_lateral_lunge_rep_generator, 'WEIGHTED_SLIDING_LATERAL_LUNGE', 'reps'),
    (weighted_sliding_lateral_lunge_hold_generator, 'WEIGHTED_SLIDING_LATERAL_LUNGE', 'hold'),
    (weighted_walking_lunge_rep_generator, 'WEIGHTED_WALKING_LUNGE', 'reps'),
    (weighted_walking_lunge_hold_generator, 'WEIGHTED_WALKING_LUNGE', 'hold'),
    (wide_grip_overhead_barbell_split_squat_rep_generator, 'WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT', 'reps'),
    (wide_grip_overhead_barbell_split_squat_hold_generator, 'WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'LUNGE'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
