import pytest

from garminworkouts.config.generators.strength.hyperextension import (
    back_extension_with_opposite_arm_and_leg_reach_rep_generator,
    back_extension_with_opposite_arm_and_leg_reach_hold_generator,
    base_rotations_rep_generator,
    base_rotations_hold_generator,
    bent_knee_reverse_hyperextension_rep_generator,
    bent_knee_reverse_hyperextension_hold_generator,
    hollow_hold_and_roll_rep_generator,
    hollow_hold_and_roll_hold_generator,
    hyperextension_rep_generator,
    hyperextension_hold_generator,
    kicks_rep_generator,
    kicks_hold_generator,
    knee_raises_rep_generator,
    knee_raises_hold_generator,
    kneeling_superman_rep_generator,
    kneeling_superman_hold_generator,
    lat_pull_down_with_row_rep_generator,
    lat_pull_down_with_row_hold_generator,
    medicine_ball_deadlift_to_reach_rep_generator,
    medicine_ball_deadlift_to_reach_hold_generator,
    one_arm_one_leg_row_rep_generator,
    one_arm_one_leg_row_hold_generator,
    one_arm_row_with_band_rep_generator,
    one_arm_row_with_band_hold_generator,
    overhead_lunge_with_medicine_ball_rep_generator,
    overhead_lunge_with_medicine_ball_hold_generator,
    plank_knee_tucks_rep_generator,
    plank_knee_tucks_hold_generator,
    side_step_rep_generator,
    side_step_hold_generator,
    single_leg_back_extension_rep_generator,
    single_leg_back_extension_hold_generator,
    spine_extension_rep_generator,
    spine_extension_hold_generator,
    static_back_extension_rep_generator,
    static_back_extension_hold_generator,
    superman_from_floor_rep_generator,
    superman_from_floor_hold_generator,
    superman_on_swiss_ball_rep_generator,
    superman_on_swiss_ball_hold_generator,
    swiss_ball_back_extension_rep_generator,
    swiss_ball_back_extension_hold_generator,
    swiss_ball_hyperextension_rep_generator,
    swiss_ball_hyperextension_hold_generator,
    swiss_ball_opposite_arm_and_leg_lift_rep_generator,
    swiss_ball_opposite_arm_and_leg_lift_hold_generator,
    weighted_back_extension_with_opposite_arm_and_leg_reach_rep_generator,
    weighted_back_extension_with_opposite_arm_and_leg_reach_hold_generator,
    weighted_base_rotations_rep_generator,
    weighted_base_rotations_hold_generator,
    weighted_bent_knee_reverse_hyperextension_rep_generator,
    weighted_bent_knee_reverse_hyperextension_hold_generator,
    weighted_hollow_hold_and_roll_rep_generator,
    weighted_hollow_hold_and_roll_hold_generator,
    weighted_kicks_rep_generator,
    weighted_kicks_hold_generator,
    weighted_knee_raises_rep_generator,
    weighted_knee_raises_hold_generator,
    weighted_kneeling_superman_rep_generator,
    weighted_kneeling_superman_hold_generator,
    weighted_plank_knee_tucks_rep_generator,
    weighted_plank_knee_tucks_hold_generator,
    weighted_side_step_rep_generator,
    weighted_side_step_hold_generator,
    weighted_single_leg_back_extension_rep_generator,
    weighted_single_leg_back_extension_hold_generator,
    weighted_spine_extension_rep_generator,
    weighted_spine_extension_hold_generator,
    weighted_static_back_extension_rep_generator,
    weighted_static_back_extension_hold_generator,
    weighted_superman_from_floor_rep_generator,
    weighted_superman_from_floor_hold_generator,
    weighted_swiss_ball_back_extension_rep_generator,
    weighted_swiss_ball_back_extension_hold_generator,
    weighted_swiss_ball_hyperextension_rep_generator,
    weighted_swiss_ball_hyperextension_hold_generator,
    weighted_swiss_ball_opposite_arm_and_leg_lift_rep_generator,
    weighted_swiss_ball_opposite_arm_and_leg_lift_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (back_extension_with_opposite_arm_and_leg_reach_rep_generator, 'BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH', 'reps'),
    (back_extension_with_opposite_arm_and_leg_reach_hold_generator, 'BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH', 'hold'),
    (base_rotations_rep_generator, 'BASE_ROTATIONS', 'reps'),
    (base_rotations_hold_generator, 'BASE_ROTATIONS', 'hold'),
    (bent_knee_reverse_hyperextension_rep_generator, 'BENT_KNEE_REVERSE_HYPEREXTENSION', 'reps'),
    (bent_knee_reverse_hyperextension_hold_generator, 'BENT_KNEE_REVERSE_HYPEREXTENSION', 'hold'),
    (hollow_hold_and_roll_rep_generator, 'HOLLOW_HOLD_AND_ROLL', 'reps'),
    (hollow_hold_and_roll_hold_generator, 'HOLLOW_HOLD_AND_ROLL', 'hold'),
    (hyperextension_rep_generator, 'HYPEREXTENSION', 'reps'),
    (hyperextension_hold_generator, 'HYPEREXTENSION', 'hold'),
    (kicks_rep_generator, 'KICKS', 'reps'),
    (kicks_hold_generator, 'KICKS', 'hold'),
    (knee_raises_rep_generator, 'KNEE_RAISES', 'reps'),
    (knee_raises_hold_generator, 'KNEE_RAISES', 'hold'),
    (kneeling_superman_rep_generator, 'KNEELING_SUPERMAN', 'reps'),
    (kneeling_superman_hold_generator, 'KNEELING_SUPERMAN', 'hold'),
    (lat_pull_down_with_row_rep_generator, 'LAT_PULL_DOWN_WITH_ROW', 'reps'),
    (lat_pull_down_with_row_hold_generator, 'LAT_PULL_DOWN_WITH_ROW', 'hold'),
    (medicine_ball_deadlift_to_reach_rep_generator, 'MEDICINE_BALL_DEADLIFT_TO_REACH', 'reps'),
    (medicine_ball_deadlift_to_reach_hold_generator, 'MEDICINE_BALL_DEADLIFT_TO_REACH', 'hold'),
    (one_arm_one_leg_row_rep_generator, 'ONE_ARM_ONE_LEG_ROW', 'reps'),
    (one_arm_one_leg_row_hold_generator, 'ONE_ARM_ONE_LEG_ROW', 'hold'),
    (one_arm_row_with_band_rep_generator, 'ONE_ARM_ROW_WITH_BAND', 'reps'),
    (one_arm_row_with_band_hold_generator, 'ONE_ARM_ROW_WITH_BAND', 'hold'),
    (overhead_lunge_with_medicine_ball_rep_generator, 'OVERHEAD_LUNGE_WITH_MEDICINE_BALL', 'reps'),
    (overhead_lunge_with_medicine_ball_hold_generator, 'OVERHEAD_LUNGE_WITH_MEDICINE_BALL', 'hold'),
    (plank_knee_tucks_rep_generator, 'PLANK_KNEE_TUCKS', 'reps'),
    (plank_knee_tucks_hold_generator, 'PLANK_KNEE_TUCKS', 'hold'),
    (side_step_rep_generator, 'SIDE_STEP', 'reps'),
    (side_step_hold_generator, 'SIDE_STEP', 'hold'),
    (single_leg_back_extension_rep_generator, 'SINGLE_LEG_BACK_EXTENSION', 'reps'),
    (single_leg_back_extension_hold_generator, 'SINGLE_LEG_BACK_EXTENSION', 'hold'),
    (spine_extension_rep_generator, 'SPINE_EXTENSION', 'reps'),
    (spine_extension_hold_generator, 'SPINE_EXTENSION', 'hold'),
    (static_back_extension_rep_generator, 'STATIC_BACK_EXTENSION', 'reps'),
    (static_back_extension_hold_generator, 'STATIC_BACK_EXTENSION', 'hold'),
    (superman_from_floor_rep_generator, 'SUPERMAN_FROM_FLOOR', 'reps'),
    (superman_from_floor_hold_generator, 'SUPERMAN_FROM_FLOOR', 'hold'),
    (superman_on_swiss_ball_rep_generator, 'SUPERMAN_ON_SWISS_BALL', 'reps'),
    (superman_on_swiss_ball_hold_generator, 'SUPERMAN_ON_SWISS_BALL', 'hold'),
    (swiss_ball_back_extension_rep_generator, 'SWISS_BALL_BACK_EXTENSION', 'reps'),
    (swiss_ball_back_extension_hold_generator, 'SWISS_BALL_BACK_EXTENSION', 'hold'),
    (swiss_ball_hyperextension_rep_generator, 'SWISS_BALL_HYPEREXTENSION', 'reps'),
    (swiss_ball_hyperextension_hold_generator, 'SWISS_BALL_HYPEREXTENSION', 'hold'),
    (swiss_ball_opposite_arm_and_leg_lift_rep_generator, 'SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT', 'reps'),
    (swiss_ball_opposite_arm_and_leg_lift_hold_generator, 'SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT', 'hold'),
    (weighted_back_extension_with_opposite_arm_and_leg_reach_rep_generator, 'WEIGHTED_BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH', 'reps'),
    (weighted_back_extension_with_opposite_arm_and_leg_reach_hold_generator, 'WEIGHTED_BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH', 'hold'),
    (weighted_base_rotations_rep_generator, 'WEIGHTED_BASE_ROTATIONS', 'reps'),
    (weighted_base_rotations_hold_generator, 'WEIGHTED_BASE_ROTATIONS', 'hold'),
    (weighted_bent_knee_reverse_hyperextension_rep_generator, 'WEIGHTED_BENT_KNEE_REVERSE_HYPEREXTENSION', 'reps'),
    (weighted_bent_knee_reverse_hyperextension_hold_generator, 'WEIGHTED_BENT_KNEE_REVERSE_HYPEREXTENSION', 'hold'),
    (weighted_hollow_hold_and_roll_rep_generator, 'WEIGHTED_HOLLOW_HOLD_AND_ROLL', 'reps'),
    (weighted_hollow_hold_and_roll_hold_generator, 'WEIGHTED_HOLLOW_HOLD_AND_ROLL', 'hold'),
    (weighted_kicks_rep_generator, 'WEIGHTED_KICKS', 'reps'),
    (weighted_kicks_hold_generator, 'WEIGHTED_KICKS', 'hold'),
    (weighted_knee_raises_rep_generator, 'WEIGHTED_KNEE_RAISES', 'reps'),
    (weighted_knee_raises_hold_generator, 'WEIGHTED_KNEE_RAISES', 'hold'),
    (weighted_kneeling_superman_rep_generator, 'WEIGHTED_KNEELING_SUPERMAN', 'reps'),
    (weighted_kneeling_superman_hold_generator, 'WEIGHTED_KNEELING_SUPERMAN', 'hold'),
    (weighted_plank_knee_tucks_rep_generator, 'WEIGHTED_PLANK_KNEE_TUCKS', 'reps'),
    (weighted_plank_knee_tucks_hold_generator, 'WEIGHTED_PLANK_KNEE_TUCKS', 'hold'),
    (weighted_side_step_rep_generator, 'WEIGHTED_SIDE_STEP', 'reps'),
    (weighted_side_step_hold_generator, 'WEIGHTED_SIDE_STEP', 'hold'),
    (weighted_single_leg_back_extension_rep_generator, 'WEIGHTED_SINGLE_LEG_BACK_EXTENSION', 'reps'),
    (weighted_single_leg_back_extension_hold_generator, 'WEIGHTED_SINGLE_LEG_BACK_EXTENSION', 'hold'),
    (weighted_spine_extension_rep_generator, 'WEIGHTED_SPINE_EXTENSION', 'reps'),
    (weighted_spine_extension_hold_generator, 'WEIGHTED_SPINE_EXTENSION', 'hold'),
    (weighted_static_back_extension_rep_generator, 'WEIGHTED_STATIC_BACK_EXTENSION', 'reps'),
    (weighted_static_back_extension_hold_generator, 'WEIGHTED_STATIC_BACK_EXTENSION', 'hold'),
    (weighted_superman_from_floor_rep_generator, 'WEIGHTED_SUPERMAN_FROM_FLOOR', 'reps'),
    (weighted_superman_from_floor_hold_generator, 'WEIGHTED_SUPERMAN_FROM_FLOOR', 'hold'),
    (weighted_swiss_ball_back_extension_rep_generator, 'WEIGHTED_SWISS_BALL_BACK_EXTENSION', 'reps'),
    (weighted_swiss_ball_back_extension_hold_generator, 'WEIGHTED_SWISS_BALL_BACK_EXTENSION', 'hold'),
    (weighted_swiss_ball_hyperextension_rep_generator, 'WEIGHTED_SWISS_BALL_HYPEREXTENSION', 'reps'),
    (weighted_swiss_ball_hyperextension_hold_generator, 'WEIGHTED_SWISS_BALL_HYPEREXTENSION', 'hold'),
    (weighted_swiss_ball_opposite_arm_and_leg_lift_rep_generator, 'WEIGHTED_SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT', 'reps'),
    (weighted_swiss_ball_opposite_arm_and_leg_lift_hold_generator, 'WEIGHTED_SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'HYPEREXTENSION'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
