import pytest

from garminworkouts.config.generators.strength.sit_up import (
    alternating_sit_up_rep_generator,
    alternating_sit_up_hold_generator,
    bent_knee_v_up_rep_generator,
    bent_knee_v_up_hold_generator,
    butterfly_sit_up_rep_generator,
    butterfly_sit_up_hold_generator,
    cross_punch_roll_up_rep_generator,
    cross_punch_roll_up_hold_generator,
    crossed_arms_sit_up_rep_generator,
    crossed_arms_sit_up_hold_generator,
    get_up_sit_up_rep_generator,
    get_up_sit_up_hold_generator,
    ghd_sit_ups_rep_generator,
    ghd_sit_ups_hold_generator,
    hovering_sit_up_rep_generator,
    hovering_sit_up_hold_generator,
    kettlebell_sit_up_rep_generator,
    kettlebell_sit_up_hold_generator,
    medicine_ball_alternating_v_up_rep_generator,
    medicine_ball_alternating_v_up_hold_generator,
    medicine_ball_sit_up_rep_generator,
    medicine_ball_sit_up_hold_generator,
    medicine_ball_v_up_rep_generator,
    medicine_ball_v_up_hold_generator,
    modified_sit_up_rep_generator,
    modified_sit_up_hold_generator,
    negative_sit_up_rep_generator,
    negative_sit_up_hold_generator,
    one_arm_full_sit_up_rep_generator,
    one_arm_full_sit_up_hold_generator,
    reclining_circle_rep_generator,
    reclining_circle_hold_generator,
    reverse_curl_up_rep_generator,
    reverse_curl_up_hold_generator,
    russian_twist_on_swiss_ball_rep_generator,
    russian_twist_on_swiss_ball_hold_generator,
    single_leg_swiss_ball_jackknife_rep_generator,
    single_leg_swiss_ball_jackknife_hold_generator,
    sit_up_rep_generator,
    sit_up_hold_generator,
    sit_up_turkish_get_up_rep_generator,
    sit_up_turkish_get_up_hold_generator,
    the_teaser_rep_generator,
    the_teaser_hold_generator,
    the_teaser_weighted_rep_generator,
    the_teaser_weighted_hold_generator,
    three_part_roll_down_rep_generator,
    three_part_roll_down_hold_generator,
    v_up_rep_generator,
    v_up_hold_generator,
    weighted_alternating_sit_up_rep_generator,
    weighted_alternating_sit_up_hold_generator,
    weighted_bent_knee_v_up_rep_generator,
    weighted_bent_knee_v_up_hold_generator,
    weighted_butterfly_situp_rep_generator,
    weighted_butterfly_situp_hold_generator,
    weighted_cross_punch_roll_up_rep_generator,
    weighted_cross_punch_roll_up_hold_generator,
    weighted_crossed_arms_sit_up_rep_generator,
    weighted_crossed_arms_sit_up_hold_generator,
    weighted_get_up_sit_up_rep_generator,
    weighted_get_up_sit_up_hold_generator,
    weighted_hovering_sit_up_rep_generator,
    weighted_hovering_sit_up_hold_generator,
    weighted_reclining_circle_rep_generator,
    weighted_reclining_circle_hold_generator,
    weighted_reverse_curl_up_rep_generator,
    weighted_reverse_curl_up_hold_generator,
    weighted_russian_twist_on_swiss_ball_rep_generator,
    weighted_russian_twist_on_swiss_ball_hold_generator,
    weighted_single_leg_swiss_ball_jackknife_rep_generator,
    weighted_single_leg_swiss_ball_jackknife_hold_generator,
    weighted_sit_up_rep_generator,
    weighted_sit_up_hold_generator,
    weighted_three_part_roll_down_rep_generator,
    weighted_three_part_roll_down_hold_generator,
    weighted_v_up_rep_generator,
    weighted_v_up_hold_generator,
    weighted_x_abs_rep_generator,
    weighted_x_abs_hold_generator,
    x_abs_rep_generator,
    x_abs_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (alternating_sit_up_rep_generator, 'ALTERNATING_SIT_UP', 'reps'),
    (alternating_sit_up_hold_generator, 'ALTERNATING_SIT_UP', 'hold'),
    (bent_knee_v_up_rep_generator, 'BENT_KNEE_V_UP', 'reps'),
    (bent_knee_v_up_hold_generator, 'BENT_KNEE_V_UP', 'hold'),
    (butterfly_sit_up_rep_generator, 'BUTTERFLY_SIT_UP', 'reps'),
    (butterfly_sit_up_hold_generator, 'BUTTERFLY_SIT_UP', 'hold'),
    (cross_punch_roll_up_rep_generator, 'CROSS_PUNCH_ROLL_UP', 'reps'),
    (cross_punch_roll_up_hold_generator, 'CROSS_PUNCH_ROLL_UP', 'hold'),
    (crossed_arms_sit_up_rep_generator, 'CROSSED_ARMS_SIT_UP', 'reps'),
    (crossed_arms_sit_up_hold_generator, 'CROSSED_ARMS_SIT_UP', 'hold'),
    (get_up_sit_up_rep_generator, 'GET_UP_SIT_UP', 'reps'),
    (get_up_sit_up_hold_generator, 'GET_UP_SIT_UP', 'hold'),
    (ghd_sit_ups_rep_generator, 'GHD_SIT_UPS', 'reps'),
    (ghd_sit_ups_hold_generator, 'GHD_SIT_UPS', 'hold'),
    (hovering_sit_up_rep_generator, 'HOVERING_SIT_UP', 'reps'),
    (hovering_sit_up_hold_generator, 'HOVERING_SIT_UP', 'hold'),
    (kettlebell_sit_up_rep_generator, 'KETTLEBELL_SIT_UP', 'reps'),
    (kettlebell_sit_up_hold_generator, 'KETTLEBELL_SIT_UP', 'hold'),
    (medicine_ball_alternating_v_up_rep_generator, 'MEDICINE_BALL_ALTERNATING_V_UP', 'reps'),
    (medicine_ball_alternating_v_up_hold_generator, 'MEDICINE_BALL_ALTERNATING_V_UP', 'hold'),
    (medicine_ball_sit_up_rep_generator, 'MEDICINE_BALL_SIT_UP', 'reps'),
    (medicine_ball_sit_up_hold_generator, 'MEDICINE_BALL_SIT_UP', 'hold'),
    (medicine_ball_v_up_rep_generator, 'MEDICINE_BALL_V_UP', 'reps'),
    (medicine_ball_v_up_hold_generator, 'MEDICINE_BALL_V_UP', 'hold'),
    (modified_sit_up_rep_generator, 'MODIFIED_SIT_UP', 'reps'),
    (modified_sit_up_hold_generator, 'MODIFIED_SIT_UP', 'hold'),
    (negative_sit_up_rep_generator, 'NEGATIVE_SIT_UP', 'reps'),
    (negative_sit_up_hold_generator, 'NEGATIVE_SIT_UP', 'hold'),
    (one_arm_full_sit_up_rep_generator, 'ONE_ARM_FULL_SIT_UP', 'reps'),
    (one_arm_full_sit_up_hold_generator, 'ONE_ARM_FULL_SIT_UP', 'hold'),
    (reclining_circle_rep_generator, 'RECLINING_CIRCLE', 'reps'),
    (reclining_circle_hold_generator, 'RECLINING_CIRCLE', 'hold'),
    (reverse_curl_up_rep_generator, 'REVERSE_CURL_UP', 'reps'),
    (reverse_curl_up_hold_generator, 'REVERSE_CURL_UP', 'hold'),
    (russian_twist_on_swiss_ball_rep_generator, 'RUSSIAN_TWIST_ON_SWISS_BALL', 'reps'),
    (russian_twist_on_swiss_ball_hold_generator, 'RUSSIAN_TWIST_ON_SWISS_BALL', 'hold'),
    (single_leg_swiss_ball_jackknife_rep_generator, 'SINGLE_LEG_SWISS_BALL_JACKKNIFE', 'reps'),
    (single_leg_swiss_ball_jackknife_hold_generator, 'SINGLE_LEG_SWISS_BALL_JACKKNIFE', 'hold'),
    (sit_up_rep_generator, 'SIT_UP', 'reps'),
    (sit_up_hold_generator, 'SIT_UP', 'hold'),
    (sit_up_turkish_get_up_rep_generator, 'SIT_UP_TURKISH_GET_UP', 'reps'),
    (sit_up_turkish_get_up_hold_generator, 'SIT_UP_TURKISH_GET_UP', 'hold'),
    (the_teaser_rep_generator, 'THE_TEASER', 'reps'),
    (the_teaser_hold_generator, 'THE_TEASER', 'hold'),
    (the_teaser_weighted_rep_generator, 'THE_TEASER_WEIGHTED', 'reps'),
    (the_teaser_weighted_hold_generator, 'THE_TEASER_WEIGHTED', 'hold'),
    (three_part_roll_down_rep_generator, 'THREE_PART_ROLL_DOWN', 'reps'),
    (three_part_roll_down_hold_generator, 'THREE_PART_ROLL_DOWN', 'hold'),
    (v_up_rep_generator, 'V_UP', 'reps'),
    (v_up_hold_generator, 'V_UP', 'hold'),
    (weighted_alternating_sit_up_rep_generator, 'WEIGHTED_ALTERNATING_SIT_UP', 'reps'),
    (weighted_alternating_sit_up_hold_generator, 'WEIGHTED_ALTERNATING_SIT_UP', 'hold'),
    (weighted_bent_knee_v_up_rep_generator, 'WEIGHTED_BENT_KNEE_V_UP', 'reps'),
    (weighted_bent_knee_v_up_hold_generator, 'WEIGHTED_BENT_KNEE_V_UP', 'hold'),
    (weighted_butterfly_situp_rep_generator, 'WEIGHTED_BUTTERFLY_SITUP', 'reps'),
    (weighted_butterfly_situp_hold_generator, 'WEIGHTED_BUTTERFLY_SITUP', 'hold'),
    (weighted_cross_punch_roll_up_rep_generator, 'WEIGHTED_CROSS_PUNCH_ROLL_UP', 'reps'),
    (weighted_cross_punch_roll_up_hold_generator, 'WEIGHTED_CROSS_PUNCH_ROLL_UP', 'hold'),
    (weighted_crossed_arms_sit_up_rep_generator, 'WEIGHTED_CROSSED_ARMS_SIT_UP', 'reps'),
    (weighted_crossed_arms_sit_up_hold_generator, 'WEIGHTED_CROSSED_ARMS_SIT_UP', 'hold'),
    (weighted_get_up_sit_up_rep_generator, 'WEIGHTED_GET_UP_SIT_UP', 'reps'),
    (weighted_get_up_sit_up_hold_generator, 'WEIGHTED_GET_UP_SIT_UP', 'hold'),
    (weighted_hovering_sit_up_rep_generator, 'WEIGHTED_HOVERING_SIT_UP', 'reps'),
    (weighted_hovering_sit_up_hold_generator, 'WEIGHTED_HOVERING_SIT_UP', 'hold'),
    (weighted_reclining_circle_rep_generator, 'WEIGHTED_RECLINING_CIRCLE', 'reps'),
    (weighted_reclining_circle_hold_generator, 'WEIGHTED_RECLINING_CIRCLE', 'hold'),
    (weighted_reverse_curl_up_rep_generator, 'WEIGHTED_REVERSE_CURL_UP', 'reps'),
    (weighted_reverse_curl_up_hold_generator, 'WEIGHTED_REVERSE_CURL_UP', 'hold'),
    (weighted_russian_twist_on_swiss_ball_rep_generator, 'WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL', 'reps'),
    (weighted_russian_twist_on_swiss_ball_hold_generator, 'WEIGHTED_RUSSIAN_TWIST_ON_SWISS_BALL', 'hold'),
    (weighted_single_leg_swiss_ball_jackknife_rep_generator, 'WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE', 'reps'),
    (weighted_single_leg_swiss_ball_jackknife_hold_generator, 'WEIGHTED_SINGLE_LEG_SWISS_BALL_JACKKNIFE', 'hold'),
    (weighted_sit_up_rep_generator, 'WEIGHTED_SIT_UP', 'reps'),
    (weighted_sit_up_hold_generator, 'WEIGHTED_SIT_UP', 'hold'),
    (weighted_three_part_roll_down_rep_generator, 'WEIGHTED_THREE_PART_ROLL_DOWN', 'reps'),
    (weighted_three_part_roll_down_hold_generator, 'WEIGHTED_THREE_PART_ROLL_DOWN', 'hold'),
    (weighted_v_up_rep_generator, 'WEIGHTED_V_UP', 'reps'),
    (weighted_v_up_hold_generator, 'WEIGHTED_V_UP', 'hold'),
    (weighted_x_abs_rep_generator, 'WEIGHTED_X_ABS', 'reps'),
    (weighted_x_abs_hold_generator, 'WEIGHTED_X_ABS', 'hold'),
    (x_abs_rep_generator, 'X_ABS', 'reps'),
    (x_abs_hold_generator, 'X_ABS', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'SIT_UP'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
