import pytest

from garminworkouts.config.generators.strength.shrug import (
    barbell_jump_shrug_rep_generator,
    barbell_jump_shrug_hold_generator,
    barbell_shrug_rep_generator,
    barbell_shrug_hold_generator,
    barbell_upright_row_rep_generator,
    barbell_upright_row_hold_generator,
    behind_the_back_shrug_rep_generator,
    behind_the_back_shrug_hold_generator,
    behind_the_back_smith_machine_shrug_rep_generator,
    behind_the_back_smith_machine_shrug_hold_generator,
    dumbbell_jump_shrug_rep_generator,
    dumbbell_jump_shrug_hold_generator,
    dumbbell_shrug_rep_generator,
    dumbbell_shrug_hold_generator,
    dumbbell_upright_row_rep_generator,
    dumbbell_upright_row_hold_generator,
    incline_dumbbell_shrug_rep_generator,
    incline_dumbbell_shrug_hold_generator,
    overhead_barbell_shrug_rep_generator,
    overhead_barbell_shrug_hold_generator,
    overhead_dumbbell_shrug_rep_generator,
    overhead_dumbbell_shrug_hold_generator,
    scaption_and_shrug_rep_generator,
    scaption_and_shrug_hold_generator,
    scapular_retraction_rep_generator,
    scapular_retraction_hold_generator,
    serratus_chair_shrug_rep_generator,
    serratus_chair_shrug_hold_generator,
    serratus_shrug_rep_generator,
    serratus_shrug_hold_generator,
    shrug_rep_generator,
    shrug_hold_generator,
    weighted_serratus_chair_shrug_rep_generator,
    weighted_serratus_chair_shrug_hold_generator,
    weighted_serratus_shrug_rep_generator,
    weighted_serratus_shrug_hold_generator,
    wide_grip_barbell_shrug_rep_generator,
    wide_grip_barbell_shrug_hold_generator,
    wide_grip_jump_shrug_rep_generator,
    wide_grip_jump_shrug_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (barbell_jump_shrug_rep_generator, 'BARBELL_JUMP_SHRUG', 'reps'),
    (barbell_jump_shrug_hold_generator, 'BARBELL_JUMP_SHRUG', 'hold'),
    (barbell_shrug_rep_generator, 'BARBELL_SHRUG', 'reps'),
    (barbell_shrug_hold_generator, 'BARBELL_SHRUG', 'hold'),
    (barbell_upright_row_rep_generator, 'BARBELL_UPRIGHT_ROW', 'reps'),
    (barbell_upright_row_hold_generator, 'BARBELL_UPRIGHT_ROW', 'hold'),
    (behind_the_back_shrug_rep_generator, 'BEHIND_THE_BACK_SHRUG', 'reps'),
    (behind_the_back_shrug_hold_generator, 'BEHIND_THE_BACK_SHRUG', 'hold'),
    (behind_the_back_smith_machine_shrug_rep_generator, 'BEHIND_THE_BACK_SMITH_MACHINE_SHRUG', 'reps'),
    (behind_the_back_smith_machine_shrug_hold_generator, 'BEHIND_THE_BACK_SMITH_MACHINE_SHRUG', 'hold'),
    (dumbbell_jump_shrug_rep_generator, 'DUMBBELL_JUMP_SHRUG', 'reps'),
    (dumbbell_jump_shrug_hold_generator, 'DUMBBELL_JUMP_SHRUG', 'hold'),
    (dumbbell_shrug_rep_generator, 'DUMBBELL_SHRUG', 'reps'),
    (dumbbell_shrug_hold_generator, 'DUMBBELL_SHRUG', 'hold'),
    (dumbbell_upright_row_rep_generator, 'DUMBBELL_UPRIGHT_ROW', 'reps'),
    (dumbbell_upright_row_hold_generator, 'DUMBBELL_UPRIGHT_ROW', 'hold'),
    (incline_dumbbell_shrug_rep_generator, 'INCLINE_DUMBBELL_SHRUG', 'reps'),
    (incline_dumbbell_shrug_hold_generator, 'INCLINE_DUMBBELL_SHRUG', 'hold'),
    (overhead_barbell_shrug_rep_generator, 'OVERHEAD_BARBELL_SHRUG', 'reps'),
    (overhead_barbell_shrug_hold_generator, 'OVERHEAD_BARBELL_SHRUG', 'hold'),
    (overhead_dumbbell_shrug_rep_generator, 'OVERHEAD_DUMBBELL_SHRUG', 'reps'),
    (overhead_dumbbell_shrug_hold_generator, 'OVERHEAD_DUMBBELL_SHRUG', 'hold'),
    (scaption_and_shrug_rep_generator, 'SCAPTION_AND_SHRUG', 'reps'),
    (scaption_and_shrug_hold_generator, 'SCAPTION_AND_SHRUG', 'hold'),
    (scapular_retraction_rep_generator, 'SCAPULAR_RETRACTION', 'reps'),
    (scapular_retraction_hold_generator, 'SCAPULAR_RETRACTION', 'hold'),
    (serratus_chair_shrug_rep_generator, 'SERRATUS_CHAIR_SHRUG', 'reps'),
    (serratus_chair_shrug_hold_generator, 'SERRATUS_CHAIR_SHRUG', 'hold'),
    (serratus_shrug_rep_generator, 'SERRATUS_SHRUG', 'reps'),
    (serratus_shrug_hold_generator, 'SERRATUS_SHRUG', 'hold'),
    (shrug_rep_generator, 'SHRUG', 'reps'),
    (shrug_hold_generator, 'SHRUG', 'hold'),
    (weighted_serratus_chair_shrug_rep_generator, 'WEIGHTED_SERRATUS_CHAIR_SHRUG', 'reps'),
    (weighted_serratus_chair_shrug_hold_generator, 'WEIGHTED_SERRATUS_CHAIR_SHRUG', 'hold'),
    (weighted_serratus_shrug_rep_generator, 'WEIGHTED_SERRATUS_SHRUG', 'reps'),
    (weighted_serratus_shrug_hold_generator, 'WEIGHTED_SERRATUS_SHRUG', 'hold'),
    (wide_grip_barbell_shrug_rep_generator, 'WIDE_GRIP_BARBELL_SHRUG', 'reps'),
    (wide_grip_barbell_shrug_hold_generator, 'WIDE_GRIP_BARBELL_SHRUG', 'hold'),
    (wide_grip_jump_shrug_rep_generator, 'WIDE_GRIP_JUMP_SHRUG', 'reps'),
    (wide_grip_jump_shrug_hold_generator, 'WIDE_GRIP_JUMP_SHRUG', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'SHRUG'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
