import pytest

from garminworkouts.config.generators.strength.calf_raise import (
    _3_way_calf_raise_rep_generator,
    _3_way_calf_raise_hold_generator,
    _3_way_single_leg_calf_raise_rep_generator,
    _3_way_single_leg_calf_raise_hold_generator,
    _3_way_weighted_calf_raise_rep_generator,
    _3_way_weighted_calf_raise_hold_generator,
    _3_way_weighted_single_leg_calf_raise_rep_generator,
    _3_way_weighted_single_leg_calf_raise_hold_generator,
    calf_raise_rep_generator,
    calf_raise_hold_generator,
    donkey_calf_raise_rep_generator,
    donkey_calf_raise_hold_generator,
    seated_calf_raise_rep_generator,
    seated_calf_raise_hold_generator,
    seated_dumbbell_toe_raise_rep_generator,
    seated_dumbbell_toe_raise_hold_generator,
    single_leg_bent_knee_calf_raise_rep_generator,
    single_leg_bent_knee_calf_raise_hold_generator,
    single_leg_decline_push_up_rep_generator,
    single_leg_decline_push_up_hold_generator,
    single_leg_donkey_calf_raise_rep_generator,
    single_leg_donkey_calf_raise_hold_generator,
    single_leg_hip_raise_with_knee_hold_rep_generator,
    single_leg_hip_raise_with_knee_hold_hold_generator,
    single_leg_standing_calf_raise_rep_generator,
    single_leg_standing_calf_raise_hold_generator,
    single_leg_standing_dumbbell_calf_raise_rep_generator,
    single_leg_standing_dumbbell_calf_raise_hold_generator,
    standing_barbell_calf_raise_rep_generator,
    standing_barbell_calf_raise_hold_generator,
    standing_calf_raise_rep_generator,
    standing_calf_raise_hold_generator,
    standing_dumbbell_calf_raise_rep_generator,
    standing_dumbbell_calf_raise_hold_generator,
    weighted_donkey_calf_raise_rep_generator,
    weighted_donkey_calf_raise_hold_generator,
    weighted_seated_calf_raise_rep_generator,
    weighted_seated_calf_raise_hold_generator,
    weighted_single_leg_bent_knee_calf_raise_rep_generator,
    weighted_single_leg_bent_knee_calf_raise_hold_generator,
    weighted_single_leg_donkey_calf_raise_rep_generator,
    weighted_single_leg_donkey_calf_raise_hold_generator,
    weighted_standing_calf_raise_rep_generator,
    weighted_standing_calf_raise_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (_3_way_calf_raise_rep_generator, '_3_WAY_CALF_RAISE', 'reps'),
    (_3_way_calf_raise_hold_generator, '_3_WAY_CALF_RAISE', 'hold'),
    (_3_way_single_leg_calf_raise_rep_generator, '_3_WAY_SINGLE_LEG_CALF_RAISE', 'reps'),
    (_3_way_single_leg_calf_raise_hold_generator, '_3_WAY_SINGLE_LEG_CALF_RAISE', 'hold'),
    (_3_way_weighted_calf_raise_rep_generator, '_3_WAY_WEIGHTED_CALF_RAISE', 'reps'),
    (_3_way_weighted_calf_raise_hold_generator, '_3_WAY_WEIGHTED_CALF_RAISE', 'hold'),
    (_3_way_weighted_single_leg_calf_raise_rep_generator, '_3_WAY_WEIGHTED_SINGLE_LEG_CALF_RAISE', 'reps'),
    (_3_way_weighted_single_leg_calf_raise_hold_generator, '_3_WAY_WEIGHTED_SINGLE_LEG_CALF_RAISE', 'hold'),
    (calf_raise_rep_generator, 'CALF_RAISE', 'reps'),
    (calf_raise_hold_generator, 'CALF_RAISE', 'hold'),
    (donkey_calf_raise_rep_generator, 'DONKEY_CALF_RAISE', 'reps'),
    (donkey_calf_raise_hold_generator, 'DONKEY_CALF_RAISE', 'hold'),
    (seated_calf_raise_rep_generator, 'SEATED_CALF_RAISE', 'reps'),
    (seated_calf_raise_hold_generator, 'SEATED_CALF_RAISE', 'hold'),
    (seated_dumbbell_toe_raise_rep_generator, 'SEATED_DUMBBELL_TOE_RAISE', 'reps'),
    (seated_dumbbell_toe_raise_hold_generator, 'SEATED_DUMBBELL_TOE_RAISE', 'hold'),
    (single_leg_bent_knee_calf_raise_rep_generator, 'SINGLE_LEG_BENT_KNEE_CALF_RAISE', 'reps'),
    (single_leg_bent_knee_calf_raise_hold_generator, 'SINGLE_LEG_BENT_KNEE_CALF_RAISE', 'hold'),
    (single_leg_decline_push_up_rep_generator, 'SINGLE_LEG_DECLINE_PUSH_UP', 'reps'),
    (single_leg_decline_push_up_hold_generator, 'SINGLE_LEG_DECLINE_PUSH_UP', 'hold'),
    (single_leg_donkey_calf_raise_rep_generator, 'SINGLE_LEG_DONKEY_CALF_RAISE', 'reps'),
    (single_leg_donkey_calf_raise_hold_generator, 'SINGLE_LEG_DONKEY_CALF_RAISE', 'hold'),
    (single_leg_hip_raise_with_knee_hold_rep_generator, 'SINGLE_LEG_HIP_RAISE_WITH_KNEE_HOLD', 'reps'),
    (single_leg_hip_raise_with_knee_hold_hold_generator, 'SINGLE_LEG_HIP_RAISE_WITH_KNEE_HOLD', 'hold'),
    (single_leg_standing_calf_raise_rep_generator, 'SINGLE_LEG_STANDING_CALF_RAISE', 'reps'),
    (single_leg_standing_calf_raise_hold_generator, 'SINGLE_LEG_STANDING_CALF_RAISE', 'hold'),
    (single_leg_standing_dumbbell_calf_raise_rep_generator, 'SINGLE_LEG_STANDING_DUMBBELL_CALF_RAISE', 'reps'),
    (single_leg_standing_dumbbell_calf_raise_hold_generator, 'SINGLE_LEG_STANDING_DUMBBELL_CALF_RAISE', 'hold'),
    (standing_barbell_calf_raise_rep_generator, 'STANDING_BARBELL_CALF_RAISE', 'reps'),
    (standing_barbell_calf_raise_hold_generator, 'STANDING_BARBELL_CALF_RAISE', 'hold'),
    (standing_calf_raise_rep_generator, 'STANDING_CALF_RAISE', 'reps'),
    (standing_calf_raise_hold_generator, 'STANDING_CALF_RAISE', 'hold'),
    (standing_dumbbell_calf_raise_rep_generator, 'STANDING_DUMBBELL_CALF_RAISE', 'reps'),
    (standing_dumbbell_calf_raise_hold_generator, 'STANDING_DUMBBELL_CALF_RAISE', 'hold'),
    (weighted_donkey_calf_raise_rep_generator, 'WEIGHTED_DONKEY_CALF_RAISE', 'reps'),
    (weighted_donkey_calf_raise_hold_generator, 'WEIGHTED_DONKEY_CALF_RAISE', 'hold'),
    (weighted_seated_calf_raise_rep_generator, 'WEIGHTED_SEATED_CALF_RAISE', 'reps'),
    (weighted_seated_calf_raise_hold_generator, 'WEIGHTED_SEATED_CALF_RAISE', 'hold'),
    (weighted_single_leg_bent_knee_calf_raise_rep_generator, 'WEIGHTED_SINGLE_LEG_BENT_KNEE_CALF_RAISE', 'reps'),
    (weighted_single_leg_bent_knee_calf_raise_hold_generator, 'WEIGHTED_SINGLE_LEG_BENT_KNEE_CALF_RAISE', 'hold'),
    (weighted_single_leg_donkey_calf_raise_rep_generator, 'WEIGHTED_SINGLE_LEG_DONKEY_CALF_RAISE', 'reps'),
    (weighted_single_leg_donkey_calf_raise_hold_generator, 'WEIGHTED_SINGLE_LEG_DONKEY_CALF_RAISE', 'hold'),
    (weighted_standing_calf_raise_rep_generator, 'WEIGHTED_STANDING_CALF_RAISE', 'reps'),
    (weighted_standing_calf_raise_hold_generator, 'WEIGHTED_STANDING_CALF_RAISE', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'CALF_RAISE'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
