import pytest

from garminworkouts.config.generators.strength.shoulder_stability import (
    _90_degree_cable_external_rotation_rep_generator,
    _90_degree_cable_external_rotation_hold_generator,
    band_external_rotation_rep_generator,
    band_external_rotation_hold_generator,
    band_internal_rotation_rep_generator,
    band_internal_rotation_hold_generator,
    bent_arm_lateral_raise_and_external_rotation_rep_generator,
    bent_arm_lateral_raise_and_external_rotation_hold_generator,
    cable_external_rotation_rep_generator,
    cable_external_rotation_hold_generator,
    cable_internal_rotation_rep_generator,
    cable_internal_rotation_hold_generator,
    dumbbell_face_pull_with_external_rotation_rep_generator,
    dumbbell_face_pull_with_external_rotation_hold_generator,
    floor_i_raise_rep_generator,
    floor_i_raise_hold_generator,
    floor_t_raise_rep_generator,
    floor_t_raise_hold_generator,
    floor_y_raise_rep_generator,
    floor_y_raise_hold_generator,
    incline_i_raise_rep_generator,
    incline_i_raise_hold_generator,
    incline_l_raise_rep_generator,
    incline_l_raise_hold_generator,
    incline_t_raise_rep_generator,
    incline_t_raise_hold_generator,
    incline_w_raise_rep_generator,
    incline_w_raise_hold_generator,
    incline_y_raise_rep_generator,
    incline_y_raise_hold_generator,
    lying_external_rotation_rep_generator,
    lying_external_rotation_hold_generator,
    lying_internal_rotation_rep_generator,
    lying_internal_rotation_hold_generator,
    seated_dumbbell_external_rotation_rep_generator,
    seated_dumbbell_external_rotation_hold_generator,
    seated_dumbbell_internal_rotation_rep_generator,
    seated_dumbbell_internal_rotation_hold_generator,
    shoulder_stability_rep_generator,
    shoulder_stability_hold_generator,
    standing_l_raise_rep_generator,
    standing_l_raise_hold_generator,
    swiss_ball_i_raise_rep_generator,
    swiss_ball_i_raise_hold_generator,
    swiss_ball_t_raise_rep_generator,
    swiss_ball_t_raise_hold_generator,
    swiss_ball_w_raise_rep_generator,
    swiss_ball_w_raise_hold_generator,
    swiss_ball_y_raise_rep_generator,
    swiss_ball_y_raise_hold_generator,
    weighted_floor_i_raise_rep_generator,
    weighted_floor_i_raise_hold_generator,
    weighted_floor_t_raise_rep_generator,
    weighted_floor_t_raise_hold_generator,
    weighted_floor_y_raise_rep_generator,
    weighted_floor_y_raise_hold_generator,
    weighted_incline_i_raise_rep_generator,
    weighted_incline_i_raise_hold_generator,
    weighted_incline_l_raise_rep_generator,
    weighted_incline_l_raise_hold_generator,
    weighted_incline_t_raise_rep_generator,
    weighted_incline_t_raise_hold_generator,
    weighted_incline_w_raise_rep_generator,
    weighted_incline_w_raise_hold_generator,
    weighted_incline_y_raise_rep_generator,
    weighted_incline_y_raise_hold_generator,
    weighted_swiss_ball_i_raise_rep_generator,
    weighted_swiss_ball_i_raise_hold_generator,
    weighted_swiss_ball_t_raise_rep_generator,
    weighted_swiss_ball_t_raise_hold_generator,
    weighted_swiss_ball_w_raise_rep_generator,
    weighted_swiss_ball_w_raise_hold_generator,
    weighted_swiss_ball_y_raise_rep_generator,
    weighted_swiss_ball_y_raise_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (_90_degree_cable_external_rotation_rep_generator, '_90_DEGREE_CABLE_EXTERNAL_ROTATION', 'reps'),
    (_90_degree_cable_external_rotation_hold_generator, '_90_DEGREE_CABLE_EXTERNAL_ROTATION', 'hold'),
    (band_external_rotation_rep_generator, 'BAND_EXTERNAL_ROTATION', 'reps'),
    (band_external_rotation_hold_generator, 'BAND_EXTERNAL_ROTATION', 'hold'),
    (band_internal_rotation_rep_generator, 'BAND_INTERNAL_ROTATION', 'reps'),
    (band_internal_rotation_hold_generator, 'BAND_INTERNAL_ROTATION', 'hold'),
    (bent_arm_lateral_raise_and_external_rotation_rep_generator, 'BENT_ARM_LATERAL_RAISE_AND_EXTERNAL_ROTATION', 'reps'),
    (bent_arm_lateral_raise_and_external_rotation_hold_generator, 'BENT_ARM_LATERAL_RAISE_AND_EXTERNAL_ROTATION', 'hold'),
    (cable_external_rotation_rep_generator, 'CABLE_EXTERNAL_ROTATION', 'reps'),
    (cable_external_rotation_hold_generator, 'CABLE_EXTERNAL_ROTATION', 'hold'),
    (cable_internal_rotation_rep_generator, 'CABLE_INTERNAL_ROTATION', 'reps'),
    (cable_internal_rotation_hold_generator, 'CABLE_INTERNAL_ROTATION', 'hold'),
    (dumbbell_face_pull_with_external_rotation_rep_generator, 'DUMBBELL_FACE_PULL_WITH_EXTERNAL_ROTATION', 'reps'),
    (dumbbell_face_pull_with_external_rotation_hold_generator, 'DUMBBELL_FACE_PULL_WITH_EXTERNAL_ROTATION', 'hold'),
    (floor_i_raise_rep_generator, 'FLOOR_I_RAISE', 'reps'),
    (floor_i_raise_hold_generator, 'FLOOR_I_RAISE', 'hold'),
    (floor_t_raise_rep_generator, 'FLOOR_T_RAISE', 'reps'),
    (floor_t_raise_hold_generator, 'FLOOR_T_RAISE', 'hold'),
    (floor_y_raise_rep_generator, 'FLOOR_Y_RAISE', 'reps'),
    (floor_y_raise_hold_generator, 'FLOOR_Y_RAISE', 'hold'),
    (incline_i_raise_rep_generator, 'INCLINE_I_RAISE', 'reps'),
    (incline_i_raise_hold_generator, 'INCLINE_I_RAISE', 'hold'),
    (incline_l_raise_rep_generator, 'INCLINE_L_RAISE', 'reps'),
    (incline_l_raise_hold_generator, 'INCLINE_L_RAISE', 'hold'),
    (incline_t_raise_rep_generator, 'INCLINE_T_RAISE', 'reps'),
    (incline_t_raise_hold_generator, 'INCLINE_T_RAISE', 'hold'),
    (incline_w_raise_rep_generator, 'INCLINE_W_RAISE', 'reps'),
    (incline_w_raise_hold_generator, 'INCLINE_W_RAISE', 'hold'),
    (incline_y_raise_rep_generator, 'INCLINE_Y_RAISE', 'reps'),
    (incline_y_raise_hold_generator, 'INCLINE_Y_RAISE', 'hold'),
    (lying_external_rotation_rep_generator, 'LYING_EXTERNAL_ROTATION', 'reps'),
    (lying_external_rotation_hold_generator, 'LYING_EXTERNAL_ROTATION', 'hold'),
    (lying_internal_rotation_rep_generator, 'LYING_INTERNAL_ROTATION', 'reps'),
    (lying_internal_rotation_hold_generator, 'LYING_INTERNAL_ROTATION', 'hold'),
    (seated_dumbbell_external_rotation_rep_generator, 'SEATED_DUMBBELL_EXTERNAL_ROTATION', 'reps'),
    (seated_dumbbell_external_rotation_hold_generator, 'SEATED_DUMBBELL_EXTERNAL_ROTATION', 'hold'),
    (seated_dumbbell_internal_rotation_rep_generator, 'SEATED_DUMBBELL_INTERNAL_ROTATION', 'reps'),
    (seated_dumbbell_internal_rotation_hold_generator, 'SEATED_DUMBBELL_INTERNAL_ROTATION', 'hold'),
    (shoulder_stability_rep_generator, 'SHOULDER_STABILITY', 'reps'),
    (shoulder_stability_hold_generator, 'SHOULDER_STABILITY', 'hold'),
    (standing_l_raise_rep_generator, 'STANDING_L_RAISE', 'reps'),
    (standing_l_raise_hold_generator, 'STANDING_L_RAISE', 'hold'),
    (swiss_ball_i_raise_rep_generator, 'SWISS_BALL_I_RAISE', 'reps'),
    (swiss_ball_i_raise_hold_generator, 'SWISS_BALL_I_RAISE', 'hold'),
    (swiss_ball_t_raise_rep_generator, 'SWISS_BALL_T_RAISE', 'reps'),
    (swiss_ball_t_raise_hold_generator, 'SWISS_BALL_T_RAISE', 'hold'),
    (swiss_ball_w_raise_rep_generator, 'SWISS_BALL_W_RAISE', 'reps'),
    (swiss_ball_w_raise_hold_generator, 'SWISS_BALL_W_RAISE', 'hold'),
    (swiss_ball_y_raise_rep_generator, 'SWISS_BALL_Y_RAISE', 'reps'),
    (swiss_ball_y_raise_hold_generator, 'SWISS_BALL_Y_RAISE', 'hold'),
    (weighted_floor_i_raise_rep_generator, 'WEIGHTED_FLOOR_I_RAISE', 'reps'),
    (weighted_floor_i_raise_hold_generator, 'WEIGHTED_FLOOR_I_RAISE', 'hold'),
    (weighted_floor_t_raise_rep_generator, 'WEIGHTED_FLOOR_T_RAISE', 'reps'),
    (weighted_floor_t_raise_hold_generator, 'WEIGHTED_FLOOR_T_RAISE', 'hold'),
    (weighted_floor_y_raise_rep_generator, 'WEIGHTED_FLOOR_Y_RAISE', 'reps'),
    (weighted_floor_y_raise_hold_generator, 'WEIGHTED_FLOOR_Y_RAISE', 'hold'),
    (weighted_incline_i_raise_rep_generator, 'WEIGHTED_INCLINE_I_RAISE', 'reps'),
    (weighted_incline_i_raise_hold_generator, 'WEIGHTED_INCLINE_I_RAISE', 'hold'),
    (weighted_incline_l_raise_rep_generator, 'WEIGHTED_INCLINE_L_RAISE', 'reps'),
    (weighted_incline_l_raise_hold_generator, 'WEIGHTED_INCLINE_L_RAISE', 'hold'),
    (weighted_incline_t_raise_rep_generator, 'WEIGHTED_INCLINE_T_RAISE', 'reps'),
    (weighted_incline_t_raise_hold_generator, 'WEIGHTED_INCLINE_T_RAISE', 'hold'),
    (weighted_incline_w_raise_rep_generator, 'WEIGHTED_INCLINE_W_RAISE', 'reps'),
    (weighted_incline_w_raise_hold_generator, 'WEIGHTED_INCLINE_W_RAISE', 'hold'),
    (weighted_incline_y_raise_rep_generator, 'WEIGHTED_INCLINE_Y_RAISE', 'reps'),
    (weighted_incline_y_raise_hold_generator, 'WEIGHTED_INCLINE_Y_RAISE', 'hold'),
    (weighted_swiss_ball_i_raise_rep_generator, 'WEIGHTED_SWISS_BALL_I_RAISE', 'reps'),
    (weighted_swiss_ball_i_raise_hold_generator, 'WEIGHTED_SWISS_BALL_I_RAISE', 'hold'),
    (weighted_swiss_ball_t_raise_rep_generator, 'WEIGHTED_SWISS_BALL_T_RAISE', 'reps'),
    (weighted_swiss_ball_t_raise_hold_generator, 'WEIGHTED_SWISS_BALL_T_RAISE', 'hold'),
    (weighted_swiss_ball_w_raise_rep_generator, 'WEIGHTED_SWISS_BALL_W_RAISE', 'reps'),
    (weighted_swiss_ball_w_raise_hold_generator, 'WEIGHTED_SWISS_BALL_W_RAISE', 'hold'),
    (weighted_swiss_ball_y_raise_rep_generator, 'WEIGHTED_SWISS_BALL_Y_RAISE', 'reps'),
    (weighted_swiss_ball_y_raise_hold_generator, 'WEIGHTED_SWISS_BALL_Y_RAISE', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'SHOULDER_STABILITY'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
