import pytest

from garminworkouts.config.generators.strength.deadlift import (
    barbell_deadlift_rep_generator,
    barbell_deadlift_hold_generator,
    barbell_straight_leg_deadlift_rep_generator,
    barbell_straight_leg_deadlift_hold_generator,
    deadlift_rep_generator,
    deadlift_hold_generator,
    romanian_deadlift_rep_generator,
    romanian_deadlift_hold_generator,
    dumbbell_deadlift_rep_generator,
    dumbbell_deadlift_hold_generator,
    dumbbell_single_leg_deadlift_to_row_rep_generator,
    dumbbell_single_leg_deadlift_to_row_hold_generator,
    dumbbell_straight_leg_deadlift_rep_generator,
    dumbbell_straight_leg_deadlift_hold_generator,
    kettlebell_deadlift_rep_generator,
    kettlebell_deadlift_hold_generator,
    kettlebell_floor_to_shelf_rep_generator,
    kettlebell_floor_to_shelf_hold_generator,
    kettlebell_sumo_deadlift_rep_generator,
    kettlebell_sumo_deadlift_hold_generator,
    one_arm_one_leg_deadlift_rep_generator,
    one_arm_one_leg_deadlift_hold_generator,
    rack_pull_rep_generator,
    rack_pull_hold_generator,
    rotational_dumbbell_straight_leg_deadlift_rep_generator,
    rotational_dumbbell_straight_leg_deadlift_hold_generator,
    single_arm_deadlift_rep_generator,
    single_arm_deadlift_hold_generator,
    single_leg_barbell_deadlift_rep_generator,
    single_leg_barbell_deadlift_hold_generator,
    single_leg_barbell_straight_leg_deadlift_rep_generator,
    single_leg_barbell_straight_leg_deadlift_hold_generator,
    single_leg_deadlift_with_barbell_rep_generator,
    single_leg_deadlift_with_barbell_hold_generator,
    single_leg_rdl_circuit_rep_generator,
    single_leg_rdl_circuit_hold_generator,
    single_leg_romanian_deadlift_circuit_rep_generator,
    single_leg_romanian_deadlift_circuit_hold_generator,
    single_leg_romanian_deadlift_with_dumbbell_rep_generator,
    single_leg_romanian_deadlift_with_dumbbell_hold_generator,
    sumo_deadlift_rep_generator,
    sumo_deadlift_hold_generator,
    sumo_deadlift_high_pull_rep_generator,
    sumo_deadlift_high_pull_hold_generator,
    trap_bar_deadlift_rep_generator,
    trap_bar_deadlift_hold_generator,
    wide_grip_barbell_deadlift_rep_generator,
    wide_grip_barbell_deadlift_hold_generator,
    straight_leg_deadlift_rep_generator,
    straight_leg_deadlift_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (barbell_deadlift_rep_generator, 'BARBELL_DEADLIFT', 'reps'),
    (barbell_deadlift_hold_generator, 'BARBELL_DEADLIFT', 'hold'),
    (barbell_straight_leg_deadlift_rep_generator, 'BARBELL_STRAIGHT_LEG_DEADLIFT', 'reps'),
    (barbell_straight_leg_deadlift_hold_generator, 'BARBELL_STRAIGHT_LEG_DEADLIFT', 'hold'),
    (deadlift_rep_generator, 'DEADLIFT', 'reps'),
    (deadlift_hold_generator, 'DEADLIFT', 'hold'),
    (romanian_deadlift_rep_generator, 'ROMANIAN_DEADLIFT', 'reps'),
    (romanian_deadlift_hold_generator, 'ROMANIAN_DEADLIFT', 'hold'),
    (dumbbell_deadlift_rep_generator, 'DUMBBELL_DEADLIFT', 'reps'),
    (dumbbell_deadlift_hold_generator, 'DUMBBELL_DEADLIFT', 'hold'),
    (dumbbell_single_leg_deadlift_to_row_rep_generator, 'DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW', 'reps'),
    (dumbbell_single_leg_deadlift_to_row_hold_generator, 'DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW', 'hold'),
    (dumbbell_straight_leg_deadlift_rep_generator, 'DUMBBELL_STRAIGHT_LEG_DEADLIFT', 'reps'),
    (dumbbell_straight_leg_deadlift_hold_generator, 'DUMBBELL_STRAIGHT_LEG_DEADLIFT', 'hold'),
    (kettlebell_deadlift_rep_generator, 'KETTLEBELL_DEADLIFT', 'reps'),
    (kettlebell_deadlift_hold_generator, 'KETTLEBELL_DEADLIFT', 'hold'),
    (kettlebell_floor_to_shelf_rep_generator, 'KETTLEBELL_FLOOR_TO_SHELF', 'reps'),
    (kettlebell_floor_to_shelf_hold_generator, 'KETTLEBELL_FLOOR_TO_SHELF', 'hold'),
    (kettlebell_sumo_deadlift_rep_generator, 'KETTLEBELL_SUMO_DEADLIFT', 'reps'),
    (kettlebell_sumo_deadlift_hold_generator, 'KETTLEBELL_SUMO_DEADLIFT', 'hold'),
    (one_arm_one_leg_deadlift_rep_generator, 'ONE_ARM_ONE_LEG_DEADLIFT', 'reps'),
    (one_arm_one_leg_deadlift_hold_generator, 'ONE_ARM_ONE_LEG_DEADLIFT', 'hold'),
    (rack_pull_rep_generator, 'RACK_PULL', 'reps'),
    (rack_pull_hold_generator, 'RACK_PULL', 'hold'),
    (rotational_dumbbell_straight_leg_deadlift_rep_generator, 'ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT', 'reps'),
    (rotational_dumbbell_straight_leg_deadlift_hold_generator, 'ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT', 'hold'),
    (single_arm_deadlift_rep_generator, 'SINGLE_ARM_DEADLIFT', 'reps'),
    (single_arm_deadlift_hold_generator, 'SINGLE_ARM_DEADLIFT', 'hold'),
    (single_leg_barbell_deadlift_rep_generator, 'SINGLE_LEG_BARBELL_DEADLIFT', 'reps'),
    (single_leg_barbell_deadlift_hold_generator, 'SINGLE_LEG_BARBELL_DEADLIFT', 'hold'),
    (single_leg_barbell_straight_leg_deadlift_rep_generator, 'SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT', 'reps'),
    (single_leg_barbell_straight_leg_deadlift_hold_generator, 'SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT', 'hold'),
    (single_leg_deadlift_with_barbell_rep_generator, 'SINGLE_LEG_DEADLIFT_WITH_BARBELL', 'reps'),
    (single_leg_deadlift_with_barbell_hold_generator, 'SINGLE_LEG_DEADLIFT_WITH_BARBELL', 'hold'),
    (single_leg_rdl_circuit_rep_generator, 'SINGLE_LEG_RDL_CIRCUIT', 'reps'),
    (single_leg_rdl_circuit_hold_generator, 'SINGLE_LEG_RDL_CIRCUIT', 'hold'),
    (single_leg_romanian_deadlift_circuit_rep_generator, 'SINGLE_LEG_ROMANIAN_DEADLIFT_CIRCUIT', 'reps'),
    (single_leg_romanian_deadlift_circuit_hold_generator, 'SINGLE_LEG_ROMANIAN_DEADLIFT_CIRCUIT', 'hold'),
    (single_leg_romanian_deadlift_with_dumbbell_rep_generator, 'SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL', 'reps'),
    (single_leg_romanian_deadlift_with_dumbbell_hold_generator, 'SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL', 'hold'),
    (sumo_deadlift_rep_generator, 'SUMO_DEADLIFT', 'reps'),
    (sumo_deadlift_hold_generator, 'SUMO_DEADLIFT', 'hold'),
    (sumo_deadlift_high_pull_rep_generator, 'SUMO_DEADLIFT_HIGH_PULL', 'reps'),
    (sumo_deadlift_high_pull_hold_generator, 'SUMO_DEADLIFT_HIGH_PULL', 'hold'),
    (trap_bar_deadlift_rep_generator, 'TRAP_BAR_DEADLIFT', 'reps'),
    (trap_bar_deadlift_hold_generator, 'TRAP_BAR_DEADLIFT', 'hold'),
    (wide_grip_barbell_deadlift_rep_generator, 'WIDE_GRIP_BARBELL_DEADLIFT', 'reps'),
    (wide_grip_barbell_deadlift_hold_generator, 'WIDE_GRIP_BARBELL_DEADLIFT', 'hold'),
    (straight_leg_deadlift_rep_generator, 'STRAIGHT_LEG_DEADLIFT', 'reps'),
    (straight_leg_deadlift_hold_generator, 'STRAIGHT_LEG_DEADLIFT', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'DEADLIFT'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
