import pytest

from garminworkouts.config.generators.strength.triceps_extension import (
    alternating_dumbbell_lying_triceps_extension_rep_generator,
    alternating_dumbbell_lying_triceps_extension_hold_generator,
    bench_dip_rep_generator,
    bench_dip_hold_generator,
    body_weight_dip_rep_generator,
    body_weight_dip_hold_generator,
    cable_kickback_rep_generator,
    cable_kickback_hold_generator,
    cable_lying_triceps_extension_rep_generator,
    cable_lying_triceps_extension_hold_generator,
    cable_overhead_triceps_extension_rep_generator,
    cable_overhead_triceps_extension_hold_generator,
    dumbbell_kickback_rep_generator,
    dumbbell_kickback_hold_generator,
    dumbbell_lying_triceps_extension_rep_generator,
    dumbbell_lying_triceps_extension_hold_generator,
    ez_bar_overhead_triceps_extension_rep_generator,
    ez_bar_overhead_triceps_extension_hold_generator,
    incline_dip_rep_generator,
    incline_dip_hold_generator,
    incline_ez_bar_lying_triceps_extension_rep_generator,
    incline_ez_bar_lying_triceps_extension_hold_generator,
    lying_dumbbell_pullover_to_extension_rep_generator,
    lying_dumbbell_pullover_to_extension_hold_generator,
    lying_ez_bar_triceps_extension_rep_generator,
    lying_ez_bar_triceps_extension_hold_generator,
    lying_triceps_extension_to_close_grip_bench_press_rep_generator,
    lying_triceps_extension_to_close_grip_bench_press_hold_generator,
    overhead_dumbbell_triceps_extension_rep_generator,
    overhead_dumbbell_triceps_extension_hold_generator,
    reclining_triceps_press_rep_generator,
    reclining_triceps_press_hold_generator,
    reverse_grip_pressdown_rep_generator,
    reverse_grip_pressdown_hold_generator,
    reverse_grip_triceps_pressdown_rep_generator,
    reverse_grip_triceps_pressdown_hold_generator,
    rope_pressdown_rep_generator,
    rope_pressdown_hold_generator,
    seated_barbell_overhead_triceps_extension_rep_generator,
    seated_barbell_overhead_triceps_extension_hold_generator,
    seated_dumbbell_overhead_triceps_extension_rep_generator,
    seated_dumbbell_overhead_triceps_extension_hold_generator,
    seated_ez_bar_overhead_triceps_extension_rep_generator,
    seated_ez_bar_overhead_triceps_extension_hold_generator,
    seated_single_arm_overhead_dumbbell_extension_rep_generator,
    seated_single_arm_overhead_dumbbell_extension_hold_generator,
    single_arm_dumbbell_overhead_triceps_extension_rep_generator,
    single_arm_dumbbell_overhead_triceps_extension_hold_generator,
    single_dumbbell_seated_overhead_triceps_extension_rep_generator,
    single_dumbbell_seated_overhead_triceps_extension_hold_generator,
    single_leg_bench_dip_and_kick_rep_generator,
    single_leg_bench_dip_and_kick_hold_generator,
    single_leg_dip_rep_generator,
    single_leg_dip_hold_generator,
    static_lying_triceps_extension_rep_generator,
    static_lying_triceps_extension_hold_generator,
    suspended_dip_rep_generator,
    suspended_dip_hold_generator,
    swiss_ball_dumbbell_lying_triceps_extension_rep_generator,
    swiss_ball_dumbbell_lying_triceps_extension_hold_generator,
    swiss_ball_ez_bar_lying_triceps_extension_rep_generator,
    swiss_ball_ez_bar_lying_triceps_extension_hold_generator,
    swiss_ball_ez_bar_overhead_triceps_extension_rep_generator,
    swiss_ball_ez_bar_overhead_triceps_extension_hold_generator,
    tabletop_dip_rep_generator,
    tabletop_dip_hold_generator,
    triceps_extension_on_floor_rep_generator,
    triceps_extension_on_floor_hold_generator,
    triceps_press_rep_generator,
    triceps_press_hold_generator,
    triceps_pressdown_rep_generator,
    triceps_pressdown_hold_generator,
    weighted_bench_dip_rep_generator,
    weighted_bench_dip_hold_generator,
    weighted_dip_rep_generator,
    weighted_dip_hold_generator,
    weighted_incline_dip_rep_generator,
    weighted_incline_dip_hold_generator,
    weighted_single_leg_bench_dip_and_kick_rep_generator,
    weighted_single_leg_bench_dip_and_kick_hold_generator,
    weighted_single_leg_dip_rep_generator,
    weighted_single_leg_dip_hold_generator,
    weighted_suspended_dip_rep_generator,
    weighted_suspended_dip_hold_generator,
    weighted_tabletop_dip_rep_generator,
    weighted_tabletop_dip_hold_generator,
    )


@pytest.mark.parametrize("generator, exercise_name, execution", [
    (alternating_dumbbell_lying_triceps_extension_rep_generator, 'ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION', 'reps'),
    (alternating_dumbbell_lying_triceps_extension_hold_generator, 'ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION', 'hold'),
    (bench_dip_rep_generator, 'BENCH_DIP', 'reps'),
    (bench_dip_hold_generator, 'BENCH_DIP', 'hold'),
    (body_weight_dip_rep_generator, 'BODY_WEIGHT_DIP', 'reps'),
    (body_weight_dip_hold_generator, 'BODY_WEIGHT_DIP', 'hold'),
    (cable_kickback_rep_generator, 'CABLE_KICKBACK', 'reps'),
    (cable_kickback_hold_generator, 'CABLE_KICKBACK', 'hold'),
    (cable_lying_triceps_extension_rep_generator, 'CABLE_LYING_TRICEPS_EXTENSION', 'reps'),
    (cable_lying_triceps_extension_hold_generator, 'CABLE_LYING_TRICEPS_EXTENSION', 'hold'),
    (cable_overhead_triceps_extension_rep_generator, 'CABLE_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (cable_overhead_triceps_extension_hold_generator, 'CABLE_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (dumbbell_kickback_rep_generator, 'DUMBBELL_KICKBACK', 'reps'),
    (dumbbell_kickback_hold_generator, 'DUMBBELL_KICKBACK', 'hold'),
    (dumbbell_lying_triceps_extension_rep_generator, 'DUMBBELL_LYING_TRICEPS_EXTENSION', 'reps'),
    (dumbbell_lying_triceps_extension_hold_generator, 'DUMBBELL_LYING_TRICEPS_EXTENSION', 'hold'),
    (ez_bar_overhead_triceps_extension_rep_generator, 'EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (ez_bar_overhead_triceps_extension_hold_generator, 'EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (incline_dip_rep_generator, 'INCLINE_DIP', 'reps'),
    (incline_dip_hold_generator, 'INCLINE_DIP', 'hold'),
    (incline_ez_bar_lying_triceps_extension_rep_generator, 'INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION', 'reps'),
    (incline_ez_bar_lying_triceps_extension_hold_generator, 'INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION', 'hold'),
    (lying_dumbbell_pullover_to_extension_rep_generator, 'LYING_DUMBBELL_PULLOVER_TO_EXTENSION', 'reps'),
    (lying_dumbbell_pullover_to_extension_hold_generator, 'LYING_DUMBBELL_PULLOVER_TO_EXTENSION', 'hold'),
    (lying_ez_bar_triceps_extension_rep_generator, 'LYING_EZ_BAR_TRICEPS_EXTENSION', 'reps'),
    (lying_ez_bar_triceps_extension_hold_generator, 'LYING_EZ_BAR_TRICEPS_EXTENSION', 'hold'),
    (lying_triceps_extension_to_close_grip_bench_press_rep_generator, 'LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS', 'reps'),
    (lying_triceps_extension_to_close_grip_bench_press_hold_generator, 'LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS', 'hold'),
    (overhead_dumbbell_triceps_extension_rep_generator, 'OVERHEAD_DUMBBELL_TRICEPS_EXTENSION', 'reps'),
    (overhead_dumbbell_triceps_extension_hold_generator, 'OVERHEAD_DUMBBELL_TRICEPS_EXTENSION', 'hold'),
    (reclining_triceps_press_rep_generator, 'RECLINING_TRICEPS_PRESS', 'reps'),
    (reclining_triceps_press_hold_generator, 'RECLINING_TRICEPS_PRESS', 'hold'),
    (reverse_grip_pressdown_rep_generator, 'REVERSE_GRIP_PRESSDOWN', 'reps'),
    (reverse_grip_pressdown_hold_generator, 'REVERSE_GRIP_PRESSDOWN', 'hold'),
    (reverse_grip_triceps_pressdown_rep_generator, 'REVERSE_GRIP_TRICEPS_PRESSDOWN', 'reps'),
    (reverse_grip_triceps_pressdown_hold_generator, 'REVERSE_GRIP_TRICEPS_PRESSDOWN', 'hold'),
    (rope_pressdown_rep_generator, 'ROPE_PRESSDOWN', 'reps'),
    (rope_pressdown_hold_generator, 'ROPE_PRESSDOWN', 'hold'),
    (seated_barbell_overhead_triceps_extension_rep_generator, 'SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (seated_barbell_overhead_triceps_extension_hold_generator, 'SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (seated_dumbbell_overhead_triceps_extension_rep_generator, 'SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (seated_dumbbell_overhead_triceps_extension_hold_generator, 'SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (seated_ez_bar_overhead_triceps_extension_rep_generator, 'SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (seated_ez_bar_overhead_triceps_extension_hold_generator, 'SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (seated_single_arm_overhead_dumbbell_extension_rep_generator, 'SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION', 'reps'),
    (seated_single_arm_overhead_dumbbell_extension_hold_generator, 'SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION', 'hold'),
    (single_arm_dumbbell_overhead_triceps_extension_rep_generator, 'SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (single_arm_dumbbell_overhead_triceps_extension_hold_generator, 'SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (single_dumbbell_seated_overhead_triceps_extension_rep_generator, 'SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (single_dumbbell_seated_overhead_triceps_extension_hold_generator, 'SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (single_leg_bench_dip_and_kick_rep_generator, 'SINGLE_LEG_BENCH_DIP_AND_KICK', 'reps'),
    (single_leg_bench_dip_and_kick_hold_generator, 'SINGLE_LEG_BENCH_DIP_AND_KICK', 'hold'),
    (single_leg_dip_rep_generator, 'SINGLE_LEG_DIP', 'reps'),
    (single_leg_dip_hold_generator, 'SINGLE_LEG_DIP', 'hold'),
    (static_lying_triceps_extension_rep_generator, 'STATIC_LYING_TRICEPS_EXTENSION', 'reps'),
    (static_lying_triceps_extension_hold_generator, 'STATIC_LYING_TRICEPS_EXTENSION', 'hold'),
    (suspended_dip_rep_generator, 'SUSPENDED_DIP', 'reps'),
    (suspended_dip_hold_generator, 'SUSPENDED_DIP', 'hold'),
    (swiss_ball_dumbbell_lying_triceps_extension_rep_generator, 'SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION', 'reps'),
    (swiss_ball_dumbbell_lying_triceps_extension_hold_generator, 'SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION', 'hold'),
    (swiss_ball_ez_bar_lying_triceps_extension_rep_generator, 'SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION', 'reps'),
    (swiss_ball_ez_bar_lying_triceps_extension_hold_generator, 'SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION', 'hold'),
    (swiss_ball_ez_bar_overhead_triceps_extension_rep_generator, 'SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'reps'),
    (swiss_ball_ez_bar_overhead_triceps_extension_hold_generator, 'SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION', 'hold'),
    (tabletop_dip_rep_generator, 'TABLETOP_DIP', 'reps'),
    (tabletop_dip_hold_generator, 'TABLETOP_DIP', 'hold'),
    (triceps_extension_on_floor_rep_generator, 'TRICEPS_EXTENSION_ON_FLOOR', 'reps'),
    (triceps_extension_on_floor_hold_generator, 'TRICEPS_EXTENSION_ON_FLOOR', 'hold'),
    (triceps_press_rep_generator, 'TRICEPS_PRESS', 'reps'),
    (triceps_press_hold_generator, 'TRICEPS_PRESS', 'hold'),
    (triceps_pressdown_rep_generator, 'TRICEPS_PRESSDOWN', 'reps'),
    (triceps_pressdown_hold_generator, 'TRICEPS_PRESSDOWN', 'hold'),
    (weighted_bench_dip_rep_generator, 'WEIGHTED_BENCH_DIP', 'reps'),
    (weighted_bench_dip_hold_generator, 'WEIGHTED_BENCH_DIP', 'hold'),
    (weighted_dip_rep_generator, 'WEIGHTED_DIP', 'reps'),
    (weighted_dip_hold_generator, 'WEIGHTED_DIP', 'hold'),
    (weighted_incline_dip_rep_generator, 'WEIGHTED_INCLINE_DIP', 'reps'),
    (weighted_incline_dip_hold_generator, 'WEIGHTED_INCLINE_DIP', 'hold'),
    (weighted_single_leg_bench_dip_and_kick_rep_generator, 'WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK', 'reps'),
    (weighted_single_leg_bench_dip_and_kick_hold_generator, 'WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK', 'hold'),
    (weighted_single_leg_dip_rep_generator, 'WEIGHTED_SINGLE_LEG_DIP', 'reps'),
    (weighted_single_leg_dip_hold_generator, 'WEIGHTED_SINGLE_LEG_DIP', 'hold'),
    (weighted_suspended_dip_rep_generator, 'WEIGHTED_SUSPENDED_DIP', 'reps'),
    (weighted_suspended_dip_hold_generator, 'WEIGHTED_SUSPENDED_DIP', 'hold'),
    (weighted_tabletop_dip_rep_generator, 'WEIGHTED_TABLETOP_DIP', 'reps'),
    (weighted_tabletop_dip_hold_generator, 'WEIGHTED_TABLETOP_DIP', 'hold'),
    ])
def test_exercise_generators(generator, exercise_name, execution):
    duration = "10reps" if execution == 'reps' else 'lap.button'
    description = exercise_name.replace('_', ' ').title() if execution == 'reps' else "10-count hold"
    result = generator(10)
    assert result['category'] == 'TRICEPS_EXTENSION'
    assert result['exerciseName'] == exercise_name
    assert result['duration'] == duration
    assert result['target'] == 'NO_TARGET'
    assert result['description'] == description
